const seedData = require("../data");
const { COURSE_ROUTE_PERMISSIONS } = require("../lib/coursesRbacPolicy");

const roleAliases = {
  super_admin: "Super Administrateur Somafrik",
  country_admin: "Admin Pays",
  school_admin: "Admin School",
  prefet: "Préfet des études",
  secretary: "Secrétaire",
  teacher: "Enseignant",
  student: "Élève / Étudiant",
  parent_student: "Parent",
};

const routePermissions = {
  ...COURSE_ROUTE_PERMISSIONS,
  "POST /api/users/:id/reset-password": [
    "Utilisateurs:UPDATE",
    "Gérer utilisateurs",
    "ALL_PRIVILEGES",
    "COUNTRY_PRIVILEGES",
  ],
  "GET /api/teachers": ["Enseignants:READ", "Voir enseignants", "Gérer enseignants", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "GET /api/teachers/:teacherCode": [
    "Enseignants:READ",
    "Voir enseignants",
    "Gérer enseignants",
    "COUNTRY_PRIVILEGES",
    "ALL_PRIVILEGES",
  ],
  "POST /api/teachers": ["Enseignants:CREATE", "Gérer enseignants", "ALL_PRIVILEGES"],
  "PATCH /api/teachers/:teacherCode": ["Enseignants:UPDATE", "Gérer enseignants", "ALL_PRIVILEGES"],
  "DELETE /api/teachers/:teacherCode": ["Enseignants:DELETE", "Gérer enseignants", "ALL_PRIVILEGES"],
  "GET /api/classes": ["Classes:READ", "Voir classes", "Gérer classes", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "GET /api/mobile-sync/l1/classes": ["Classes:READ", "Voir classes", "Gérer classes", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "GET /api/mobile-sync/l1/students": ["Élèves:READ", "Gérer élèves", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "POST /api/classes": ["Classes:CREATE", "Gérer classes", "ALL_PRIVILEGES"],
  "PATCH /api/classes/:classCode": ["Classes:UPDATE", "Gérer classes", "ALL_PRIVILEGES"],
  "GET /api/classes/:classCode/students": ["Élèves:READ", "Gérer élèves", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "POST /api/classes/:classCode/students": ["Élèves:CREATE", "Gérer élèves", "ALL_PRIVILEGES"],
  "GET /api/students": ["Élèves:READ", "Gérer élèves", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "GET /api/students/:id": ["Élèves:READ", "Gérer élèves", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "PATCH /api/students/:id": ["Élèves:UPDATE", "Gérer élèves", "ALL_PRIVILEGES"],
  "GET /api/assignments": [
    "Affectations:READ",
    "Enseignants:READ",
    "COUNTRY_PRIVILEGES",
    "ALL_PRIVILEGES",
  ],
  "POST /api/assignments": [
    "Affectations:CREATE",
    "ALL_PRIVILEGES",
  ],
  "PATCH /api/assignments/:assignmentId": [
    "Affectations:UPDATE",
    "ALL_PRIVILEGES",
  ],
  "DELETE /api/assignments/:assignmentId": [
    "Affectations:DELETE",
    "ALL_PRIVILEGES",
  ],
  "GET /api/payments": ["Paiements:READ", "Gérer paiements", "Voir paiements", "Voir rapports financiers", "Suivre abonnements pays", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "POST /api/payments": ["Paiements:CREATE", "Paiements:UPDATE", "Gérer paiements", "ALL_PRIVILEGES", "COUNTRY_PRIVILEGES"],
  "GET /api/v2/subjects": [
    "Matières:READ",
    "Affectations:READ",
    "Affectations:CREATE",
    "Classes:READ",
    "Gérer cours",
    "Voir classes",
    "Modifier notes",
    "Organiser examens",
    "COUNTRY_PRIVILEGES",
    "ALL_PRIVILEGES",
  ],
  "POST /api/v2/subjects": ["Matières:CREATE", "Gérer cours", "ALL_PRIVILEGES"],
  "DELETE /api/v2/subjects/:code": ["Matières:DELETE", "Gérer cours", "ALL_PRIVILEGES"],
  "GET /api/v2/academic-years": ["Années Académiques:READ", "ALL_PRIVILEGES"],
  "POST /api/v2/academic-years": ["Années Académiques:CREATE", "ALL_PRIVILEGES"],
  "PATCH /api/v2/academic-years/:id": ["Années Académiques:UPDATE", "ALL_PRIVILEGES"],
  "GET /api/v2/exams": ["Examens:READ", "Valider examens", "Organiser examens", "Gérer cours", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "GET /api/v2/documents": ["Documents:READ", "Valider bulletins", "Voir rapports", "Gérer élèves", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "GET /api/v2/reports/advanced": ["Rapports:READ", "Voir rapports globaux", "Voir rapports pays", "Voir rapports", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "GET /api/backoffice/countries": ["Contrôler tous les pays", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "POST /api/backoffice/countries": ["Contrôler tous les pays", "ALL_PRIVILEGES"],
  "PATCH /api/backoffice/countries/:code": ["Contrôler tous les pays", "ALL_PRIVILEGES"],
  "GET /api/backoffice/subscriptions": ["Gérer abonnements", "Suivre abonnements pays", "ALL_PRIVILEGES"],
  "POST /api/backoffice/subscriptions": ["Gérer abonnements", "ALL_PRIVILEGES", "COUNTRY_PRIVILEGES"],
  "PATCH /api/backoffice/subscriptions/:subscriptionId": ["Gérer abonnements", "ALL_PRIVILEGES", "COUNTRY_PRIVILEGES"],
  "GET /api/backoffice/notifications": ["ALL_PRIVILEGES", "COUNTRY_PRIVILEGES"],
  "POST /api/backoffice/notifications": ["ALL_PRIVILEGES", "COUNTRY_PRIVILEGES"],
  "PATCH /api/backoffice/notifications/:notificationId": ["ALL_PRIVILEGES", "COUNTRY_PRIVILEGES"],
  "GET /api/backoffice/role-permissions": ["ALL_PRIVILEGES"],
  "PUT /api/backoffice/role-permissions": ["ALL_PRIVILEGES"],
  "GET /api/backoffice/rbac/catalog": ["ALL_PRIVILEGES"],
  "GET /api/backoffice/rbac/permissions": ["ALL_PRIVILEGES"],
  "GET /api/backoffice/rbac/permissions/effective": ["ALL_PRIVILEGES"],
  "PATCH /api/backoffice/rbac/permissions": ["ALL_PRIVILEGES"],
  "POST /api/backoffice/rbac/roles": ["ALL_PRIVILEGES", "Rôles Établissement:CREATE"],
  "PATCH /api/backoffice/rbac/roles/:roleId": ["ALL_PRIVILEGES", "Rôles Établissement:UPDATE"],
  "POST /api/backoffice/rbac/roles/:roleId/archive": ["ALL_PRIVILEGES", "Rôles Établissement:UPDATE"],
  "DELETE /api/students/:id": ["Élèves:DELETE", "Gérer élèves", "ALL_PRIVILEGES"],
  "GET /api/backoffice/dashboard-chart-config": ["ALL_PRIVILEGES"],
  "PUT /api/backoffice/dashboard-chart-config": ["ALL_PRIVILEGES"],
  "POST /api/backoffice/subscription-offers": ["Gérer abonnements", "ALL_PRIVILEGES"],
  "PATCH /api/backoffice/subscription-offers/:offerId": ["Gérer abonnements", "ALL_PRIVILEGES"],
  "POST /api/backoffice/subscription-payments": ["Gérer abonnements", "ALL_PRIVILEGES", "COUNTRY_PRIVILEGES"],
  "PATCH /api/backoffice/subscription-payments/:paymentId": ["Gérer abonnements", "ALL_PRIVILEGES", "COUNTRY_PRIVILEGES"],
  "POST /api/backoffice/subscription-discounts": ["Gérer abonnements", "ALL_PRIVILEGES", "COUNTRY_PRIVILEGES"],
  "PATCH /api/backoffice/subscription-discounts/:discountId": ["Gérer abonnements", "ALL_PRIVILEGES", "COUNTRY_PRIVILEGES"],
  "GET /api/backoffice/establishments": ["Établissements:READ", "Gérer établissements", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "GET /api/backoffice/establishments/:code": ["Établissements:READ", "Paramètres Établissement:READ", "Gérer établissements", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "POST /api/backoffice/establishments": ["Établissements:CREATE", "Gérer établissements", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "PATCH /api/backoffice/establishments/:code": ["Établissements:UPDATE", "Paramètres Établissement:UPDATE", "Gérer établissements", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "DELETE /api/backoffice/establishments/:code": ["Établissements:DELETE", "ALL_PRIVILEGES"],
  "POST /api/backoffice/establishments/import": ["Établissements:CREATE", "Gérer établissements", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "POST /api/backoffice/import/students/validate": ["Élèves:CREATE", "Gérer élèves", "Gérer établissements", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "GET /api/backoffice/subscription-access": ["ALL_PRIVILEGES", "COUNTRY_PRIVILEGES"],
  "GET /api/backoffice/finance/unpaid": ["Impayés:READ", "Paiements:READ", "Frais & tarifs:READ", "Gérer paiements", "ALL_PRIVILEGES", "COUNTRY_PRIVILEGES"],
  "POST /api/backoffice/finance/unpaid/reminders": ["Impayés:CREATE", "Paiements:UPDATE", "Gérer paiements", "ALL_PRIVILEGES"],
  "GET /api/backoffice/users": ["Utilisateurs:READ", "Gérer utilisateurs", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "POST /api/backoffice/users": ["Utilisateurs:CREATE", "Gérer utilisateurs", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "POST /api/backoffice/users/provision": ["Utilisateurs:CREATE", "Gérer utilisateurs", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "POST /api/backoffice/users/create-teacher": [
    "Utilisateurs:CREATE",
    "Gérer utilisateurs",
    "COUNTRY_PRIVILEGES",
    "ALL_PRIVILEGES",
  ],
  "PATCH /api/backoffice/users/:userId": ["Utilisateurs:UPDATE", "Gérer utilisateurs", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "POST /api/backoffice/users/:userId/reassign-school": ["Utilisateurs:UPDATE", "Gérer utilisateurs", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "POST /api/backoffice/users/:userId/roles/grant": ["Utilisateurs:UPDATE", "Gérer utilisateurs", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "POST /api/backoffice/users/:userId/roles/revoke": ["Utilisateurs:UPDATE", "Gérer utilisateurs", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "GET /api/backoffice/users/assignable-roles": ["Utilisateurs:READ", "Gérer utilisateurs", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "GET /api/backoffice/contacts": ["Contacts:READ", "Gérer utilisateurs", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "POST /api/backoffice/contacts": ["Contacts:CREATE", "Gérer utilisateurs", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "PATCH /api/backoffice/contacts/:contactId": ["Contacts:UPDATE", "Gérer utilisateurs", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "POST /api/backoffice/contacts/:contactId/provision-account": ["Contacts:CREATE", "Gérer utilisateurs", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "GET /api/backoffice/relations": ["Relations:READ", "Gérer utilisateurs", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "POST /api/backoffice/relations": ["Relations:CREATE", "Gérer utilisateurs", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "GET /api/parents/identity": ["Relations:CREATE", "Gérer utilisateurs", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "POST /api/parents/link": ["Relations:CREATE", "Gérer utilisateurs", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "PATCH /api/parents/relations/:relationId": ["Relations:UPDATE", "Relations:CREATE", "Gérer utilisateurs", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "GET /api/backoffice/messages": ["Messages:READ", "Gérer messages", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "POST /api/backoffice/messages": ["Messages:CREATE", "Gérer messages", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "PATCH /api/backoffice/messages/:messageId/read": ["Messages:UPDATE", "Gérer messages", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "GET /api/backoffice/announcements": ["Notifications:READ", "Gérer notifications", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "POST /api/backoffice/announcements": ["Notifications:CREATE", "Gérer notifications", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "PATCH /api/backoffice/announcements/:announcementId": ["Notifications:UPDATE", "Gérer notifications", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "POST /api/backoffice/announcements/:announcementId/archive": ["Notifications:UPDATE", "Gérer notifications", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "GET /api/academic-config": [
    "Paramètres Établissement:READ",
    "Paramètres Établissement:UPDATE",
    "Référentiels pédagogiques:READ",
    "Classes:READ",
    "Voir classes",
    "Gérer classes",
    "Gérer planning académique",
    "ALL_PRIVILEGES",
    "COUNTRY_PRIVILEGES",
  ],
  "PUT /api/academic-config": [
    "Gérer planning académique",
    "Gérer classes",
    "Paramètres Établissement:UPDATE",
    "ALL_PRIVILEGES",
    "COUNTRY_PRIVILEGES",
  ],
  "GET /api/backoffice/establishments/:schoolCode/academic-config": [
    "Gérer planning académique",
    "Gérer classes",
    "Paramètres Établissement:READ",
    "Paramètres Établissement:UPDATE",
    "ALL_PRIVILEGES",
    "COUNTRY_PRIVILEGES",
  ],
  "PUT /api/backoffice/establishments/:schoolCode/academic-config": [
    "Gérer planning académique",
    "Gérer classes",
    "Paramètres Établissement:UPDATE",
    "ALL_PRIVILEGES",
    "COUNTRY_PRIVILEGES",
  ],
  "GET /api/backoffice/education-levels": ["Référentiels pédagogiques:READ", "Contrôler tous les pays", "ALL_PRIVILEGES", "COUNTRY_PRIVILEGES"],
  "POST /api/backoffice/education-levels": ["Référentiels pédagogiques:CREATE", "ALL_PRIVILEGES"],
  "PATCH /api/backoffice/education-levels/:levelId": ["Référentiels pédagogiques:UPDATE", "ALL_PRIVILEGES"],
  "POST /api/backoffice/education-levels/:levelId/archive": ["Référentiels pédagogiques:UPDATE", "ALL_PRIVILEGES"],
  "GET /api/backoffice/education-streams": ["Référentiels pédagogiques:READ", "Contrôler tous les pays", "ALL_PRIVILEGES", "COUNTRY_PRIVILEGES"],
  "POST /api/backoffice/education-streams": ["Référentiels pédagogiques:CREATE", "ALL_PRIVILEGES"],
  "PATCH /api/backoffice/education-streams/:streamId": ["Référentiels pédagogiques:UPDATE", "ALL_PRIVILEGES"],
  "POST /api/backoffice/education-streams/:streamId/archive": ["Référentiels pédagogiques:UPDATE", "ALL_PRIVILEGES"],
  "GET /api/backoffice/education-class-groups": ["Référentiels pédagogiques:READ", "Contrôler tous les pays", "ALL_PRIVILEGES", "COUNTRY_PRIVILEGES"],
  "POST /api/backoffice/education-class-groups": ["Référentiels pédagogiques:CREATE", "ALL_PRIVILEGES"],
  "PATCH /api/backoffice/education-class-groups/:groupId": ["Référentiels pédagogiques:UPDATE", "ALL_PRIVILEGES"],
  "POST /api/backoffice/education-class-groups/:groupId/archive": ["Référentiels pédagogiques:UPDATE", "ALL_PRIVILEGES"],
  "PATCH /api/backoffice/education-reference/labels": ["Référentiels pédagogiques:UPDATE", "ALL_PRIVILEGES"],
  "GET /api/education-reference/catalog": [
    "Paramètres Établissement:READ",
    "Paramètres Établissement:UPDATE",
    "Gérer classes",
    "Gérer planning académique",
    "Référentiels pédagogiques:READ",
    "ALL_PRIVILEGES",
    "COUNTRY_PRIVILEGES",
  ],
  "PUT /api/education-reference/school-activation": [
    "Paramètres Établissement:UPDATE",
    "Référentiels pédagogiques:UPDATE",
    "ALL_PRIVILEGES",
  ],
  "GET /api/backoffice/establishments/:schoolCode/education-reference/catalog": [
    "Paramètres Établissement:READ",
    "Paramètres Établissement:UPDATE",
    "Gérer classes",
    "Référentiels pédagogiques:READ",
    "ALL_PRIVILEGES",
    "COUNTRY_PRIVILEGES",
  ],
  "PUT /api/backoffice/establishments/:schoolCode/education-reference/school-activation": [
    "Paramètres Établissement:UPDATE",
    "Référentiels pédagogiques:UPDATE",
    "ALL_PRIVILEGES",
  ],
  "GET /api/backoffice/establishment-roles": ["Rôles Établissement:READ", "ALL_PRIVILEGES"],
  "POST /api/backoffice/establishment-roles": ["Rôles Établissement:CREATE", "ALL_PRIVILEGES"],
  "PATCH /api/backoffice/establishment-roles/:roleId": ["Rôles Établissement:UPDATE", "ALL_PRIVILEGES"],
  "POST /api/backoffice/establishment-roles/:roleId/archive": ["Rôles Établissement:UPDATE", "ALL_PRIVILEGES"],
  "GET /api/establishment-roles/assignable": [
    "Paramètres Établissement:READ",
    "Paramètres Établissement:UPDATE",
    "Utilisateurs:READ",
    "Utilisateurs:UPDATE",
    "Gérer utilisateurs",
    "ALL_PRIVILEGES",
  ],
  "GET /api/evaluation-types": [
    "Paramètres Établissement:READ",
    "Paramètres Établissement:UPDATE",
    "Gérer planning académique",
    "Gérer classes",
    "Notes:READ",
    "Notes:CREATE",
    "Notes:UPDATE",
    "Modifier notes",
    "Voir notes",
    "ALL_PRIVILEGES",
    "COUNTRY_PRIVILEGES",
  ],
  "POST /api/evaluation-types": [
    "Paramètres Établissement:UPDATE",
    "Gérer planning académique",
    "ALL_PRIVILEGES",
  ],
  "PATCH /api/evaluation-types/:typeId": [
    "Paramètres Établissement:UPDATE",
    "Gérer planning académique",
    "ALL_PRIVILEGES",
  ],
  "POST /api/evaluation-types/:typeId/archive": [
    "Paramètres Établissement:UPDATE",
    "Gérer planning académique",
    "ALL_PRIVILEGES",
  ],
  "GET /api/data-export": [
    "Paramètres Établissement:READ",
    "Paramètres Établissement:UPDATE",
    "Gérer planning académique",
    "ALL_PRIVILEGES",
    "COUNTRY_PRIVILEGES",
  ],
  "GET /api/school-settings": [
    "Paramètres Établissement:READ",
    "Paramètres Établissement:UPDATE",
    "Gérer planning académique",
    "Gérer classes",
    "ALL_PRIVILEGES",
    "COUNTRY_PRIVILEGES",
  ],
  "PATCH /api/school-settings": [
    "Paramètres Établissement:UPDATE",
    "Gérer planning académique",
    "ALL_PRIVILEGES",
  ],
  "PUT /api/academic-periods": [
    "Paramètres Établissement:UPDATE",
    "Gérer planning académique",
    "ALL_PRIVILEGES",
  ],
  "GET /api/backoffice/establishments/:schoolCode/school-settings": [
    "Paramètres Établissement:READ",
    "Paramètres Établissement:UPDATE",
    "Gérer planning académique",
    "ALL_PRIVILEGES",
    "COUNTRY_PRIVILEGES",
  ],
  "PATCH /api/backoffice/establishments/:schoolCode/school-settings": [
    "Paramètres Établissement:UPDATE",
    "Gérer planning académique",
    "ALL_PRIVILEGES",
  ],
  "PUT /api/backoffice/establishments/:schoolCode/academic-periods": [
    "Paramètres Établissement:UPDATE",
    "Gérer planning académique",
    "ALL_PRIVILEGES",
  ],
  "GET /api/backoffice/establishments/:schoolCode/evaluation-types": [
    "Paramètres Établissement:READ",
    "Paramètres Établissement:UPDATE",
    "Gérer planning académique",
    "Référentiels pédagogiques:READ",
    "ALL_PRIVILEGES",
    "COUNTRY_PRIVILEGES",
  ],
  "POST /api/backoffice/establishments/:schoolCode/evaluation-types": [
    "Paramètres Établissement:UPDATE",
    "Gérer planning académique",
    "ALL_PRIVILEGES",
  ],
  "PATCH /api/backoffice/establishments/:schoolCode/evaluation-types/:typeId": [
    "Paramètres Établissement:UPDATE",
    "Gérer planning académique",
    "ALL_PRIVILEGES",
  ],
  "POST /api/backoffice/establishments/:schoolCode/evaluation-types/:typeId/archive": [
    "Paramètres Établissement:UPDATE",
    "Gérer planning académique",
    "ALL_PRIVILEGES",
  ],
  "GET /api/exams": [
    "Examens:READ",
    "Valider examens",
    "Organiser examens",
    "Gérer cours",
    "COUNTRY_PRIVILEGES",
    "ALL_PRIVILEGES",
  ],
  "GET /api/exams/:examId": [
    "Examens:READ",
    "Valider examens",
    "Organiser examens",
    "Gérer cours",
    "COUNTRY_PRIVILEGES",
    "ALL_PRIVILEGES",
  ],
  "POST /api/exams": ["Organiser examens", "Valider examens", "Examens:CREATE", "Examens:UPDATE", "ALL_PRIVILEGES"],
  "PATCH /api/exams/:examId": ["Organiser examens", "Valider examens", "Examens:UPDATE", "ALL_PRIVILEGES"],
  "POST /api/exams/:examId/validate": ["Valider examens", "Examens:UPDATE", "ALL_PRIVILEGES"],
  "POST /api/exams/:examId/cancel": ["Organiser examens", "Valider examens", "Examens:UPDATE", "ALL_PRIVILEGES"],
  "POST /api/exams/:examId/archive": ["Organiser examens", "Valider examens", "Examens:UPDATE", "Examens:DELETE", "ALL_PRIVILEGES"],
  "GET /api/report-cards": ["Bulletins:READ", "Valider bulletins", "Voir rapports", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "POST /api/report-cards/generate": ["Bulletins:UPDATE", "Valider bulletins", "ALL_PRIVILEGES"],
  "POST /api/report-cards/:cardId/publish": ["Bulletins:UPDATE", "Valider bulletins", "ALL_PRIVILEGES"],
  "POST /api/report-cards/:cardId/archive": ["Bulletins:UPDATE", "Valider bulletins", "ALL_PRIVILEGES"],
  "GET /api/report-card-templates": ["Documents:READ", "Valider bulletins", "Conception bulletins", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "PUT /api/report-card-templates": ["Documents:UPDATE", "Conception bulletins", "ALL_PRIVILEGES"],
  "POST /api/report-card-templates/:templateId/archive": ["Documents:UPDATE", "Conception bulletins", "ALL_PRIVILEGES"],
  "GET /api/school-documents": ["Documents:READ", "Valider bulletins", "Voir rapports", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "POST /api/school-documents": ["Documents:CREATE", "Documents:UPDATE", "ALL_PRIVILEGES"],
  "PATCH /api/school-documents/:documentId": ["Documents:UPDATE", "ALL_PRIVILEGES"],
  "POST /api/school-documents/:documentId/archive": ["Documents:UPDATE", "ALL_PRIVILEGES"],
  "PUT /api/backoffice/planning-exams": [
    "Organiser examens",
    "Valider examens",
    "Examens:CREATE",
    "Examens:UPDATE",
    "Gérer planning académique",
    "Gérer cours",
    "ALL_PRIVILEGES",
  ],
  "GET /api/backoffice/planning-exams": [
    "Examens:READ",
    "Valider examens",
    "Organiser examens",
    "Gérer planning académique",
    "Gérer cours",
    "COUNTRY_PRIVILEGES",
    "ALL_PRIVILEGES",
  ],
  "PUT /api/backoffice/report-cards": [
    "Valider bulletins",
    "Bulletins:CREATE",
    "Bulletins:UPDATE",
    "Gérer planning académique",
    "ALL_PRIVILEGES",
    "COUNTRY_PRIVILEGES",
  ],
  "GET /api/backoffice/report-cards": [
    "Bulletins:READ",
    "Valider bulletins",
    "Gérer planning académique",
    "COUNTRY_PRIVILEGES",
    "ALL_PRIVILEGES",
  ],
  "PUT /api/backoffice/establishment-documents": [
    "Documents:CREATE",
    "Documents:UPDATE",
    "Gérer élèves",
    "Valider bulletins",
    "ALL_PRIVILEGES",
  ],
  "GET /api/backoffice/establishment-documents": [
    "Documents:READ",
    "Valider bulletins",
    "Voir rapports",
    "Gérer élèves",
    "COUNTRY_PRIVILEGES",
    "ALL_PRIVILEGES",
  ],
  "GET /api/presences": ["Présences:READ", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "GET /api/students/:id/presences": ["Présences:READ", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "POST /api/presences": ["Présences:CREATE", "Présences:UPDATE", "ALL_PRIVILEGES"],
  "GET /api/notes": ["Notes:READ", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "GET /api/students/:id/notes": ["Notes:READ", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "GET /api/evaluations": ["Notes:READ", "COUNTRY_PRIVILEGES", "ALL_PRIVILEGES"],
  "POST /api/notes": ["Notes:CREATE", "Notes:UPDATE", "ALL_PRIVILEGES"],
  "POST /api/evaluations": ["Notes:CREATE", "Notes:UPDATE", "ALL_PRIVILEGES"],
  "PATCH /api/evaluations/:evaluationId": ["Notes:UPDATE", "ALL_PRIVILEGES"],
  "GET /api/course-schedules": ["Planning de cours:READ", "ALL_PRIVILEGES"],
  "POST /api/course-schedules": ["Planning de cours:CREATE", "ALL_PRIVILEGES"],
  "PATCH /api/course-schedules/:scheduleId": ["Planning de cours:UPDATE", "ALL_PRIVILEGES"],
  "DELETE /api/course-schedules/:scheduleId": ["Planning de cours:DELETE", "ALL_PRIVILEGES"],
  "GET /api/school-rooms": ["Salles:READ", "ALL_PRIVILEGES"],
  "POST /api/school-rooms": ["Salles:CREATE", "ALL_PRIVILEGES"],
  "PATCH /api/school-rooms/:roomId": ["Salles:UPDATE", "ALL_PRIVILEGES"],
  "DELETE /api/school-rooms/:roomId": ["Salles:DELETE", "ALL_PRIVILEGES"],
  "GET /api/course-schedule-replacements": ["Remplacements:READ", "ALL_PRIVILEGES"],
  "GET /api/course-schedule-replacements/options": ["Remplacements:CREATE", "ALL_PRIVILEGES"],
  "POST /api/course-schedule-replacements": ["Remplacements:CREATE", "ALL_PRIVILEGES"],
  "PATCH /api/course-schedule-replacements/:replacementId": ["Remplacements:UPDATE", "ALL_PRIVILEGES"],
  "DELETE /api/course-schedule-replacements/:replacementId": ["Remplacements:DELETE", "ALL_PRIVILEGES"],
};

const PERMISSION_DENIED = "PERMISSION_DENIED";

class RbacService {
  constructor(rolePermissions = seedData.rolePermissions) {
    this.rolePermissions = rolePermissions;
  }

  permissionsFor(role) {
    const label = roleAliases[role] ?? role;
    return this.rolePermissions[label] ?? ["Voir tableau de bord"];
  }

  canAccess(principal, routeKey) {
    if (process.env.SOMAFRIK_AUTH_OPTIONAL === "true") {
      return true;
    }

    const requiredPermissions = routePermissions[routeKey];
    if (!Array.isArray(requiredPermissions) || requiredPermissions.length === 0) {
      return false;
    }

    if (!principal) {
      return false;
    }

    const permissions = new Set(principal.permissions ?? this.permissionsFor(principal.role));
    return requiredPermissions.some((permission) => permissions.has(permission));
  }
}

module.exports = { RbacService, routePermissions, PERMISSION_DENIED };