import {
  AUTHENTICATED_HELP_ROLES,
  ESTABLISHMENT_ADMIN_ROLES,
  SCHOOL_SETTINGS_ROLES,
  HELP_PLATFORM,
  HELP_ROLE,
  HELP_SCREEN,
  SCHOOL_STAFF_ROLES,
} from "./constants.js";
import { HELP_CATEGORY } from "./categories.js";

const WEB = HELP_PLATFORM.WEB;
const MOBILE = HELP_PLATFORM.MOBILE;
const BOTH = Object.freeze([WEB, MOBILE]);

function nav(webPath, mobileRoute, permission) {
  return { webPath, mobileRoute, permission };
}

/**
 * Articles ajoutés pour aligner le guide utilisateur in-app sur le produit actuel.
 * Aucun workflow legacy (ajout global d’élève, notes write P1, parent-enfant write).
 */
export const REFRESH_ARTICLES = [
  {
    id: "help/start/first-login",
    title: "Première connexion",
    summary:
      "La connexion se fait avec les identifiants remis par l’établissement. Un mot de passe temporaire doit être changé avant d’utiliser Somafrik.",
    category: HELP_CATEGORY.DEMARRAGE,
    order: 10,
    roles: AUTHENTICATED_HELP_ROLES,
    permissions: [],
    platforms: BOTH,
    routeKeys: Object.freeze([HELP_SCREEN.DASHBOARD, HELP_SCREEN.PARENT_HOME, HELP_SCREEN.STUDENT_HOME]),
    keywords: Object.freeze([
      "connexion",
      "première connexion",
      "identifiant",
      "mot de passe",
      "pin",
      "code établissement",
      "se connecter",
    ]),
    steps: Object.freeze([
      "Web : ouvrez Connexion. Choisissez Super administrateur, Administrateur pays ou Établissement.",
      "Pour un compte d’établissement sur le Web : renseignez Code établissement, Identifiant et Mot de passe, puis Se connecter.",
      "Mobile : saisissez Identifiant et Mot de passe, ou le PIN à 6 chiffres pour un parent ou un élève, puis Se connecter.",
      "Si Somafrik ouvre Nouveau mot de passe, saisissez le nouveau mot de passe et la Confirmation. Sur le Web, Enregistrer. Sur Mobile, Valider.",
      "Il n’existe pas d’écran « mot de passe oublié ». Demandez à un administrateur d’établissement d’utiliser Réinitialiser le mot de passe depuis Comptes utilisateurs.",
    ]),
    relatedArticles: Object.freeze(["help/account/password", "help/start/navigation", "help/assistance/contact"]),
    captureIds: [],
    captureStatus: "guide-only",
    sourceGuide: "both",
    popular: true,
    navigate: null,
  },
  {
    id: "help/start/navigation",
    title: "Navigation dans Somafrik",
    summary: "Web et Mobile n’affichent pas les mêmes menus. Seuls les modules autorisés pour votre rôle apparaissent.",
    category: HELP_CATEGORY.DEMARRAGE,
    order: 20,
    roles: AUTHENTICATED_HELP_ROLES,
    permissions: [],
    platforms: BOTH,
    routeKeys: Object.freeze([HELP_SCREEN.DASHBOARD, HELP_SCREEN.PARENT_HOME, HELP_SCREEN.STUDENT_HOME]),
    keywords: Object.freeze(["navigation", "menu", "onglets", "sidebar", "web", "mobile"]),
    steps: Object.freeze([
      "Web : le menu de gauche groupe Tableau de bord, Établissement, Pédagogie, Finances et Paramètres. Messages, Annonces et Notifications s’ouvrent depuis la barre supérieure.",
      "Mobile : la barre du bas montre jusqu’à quatre onglets selon le rôle. Le menu (tiroir) complète Accueil avec Quotidien, Admin et Outils.",
      "Un écran Web n’est pas automatiquement un écran Mobile. Le site Web redimensionné n’est pas l’application Mobile Expo.",
      "Si une entrée de menu n’apparaît pas, votre rôle n’a pas cette permission. Voir Je ne vois pas un bouton.",
    ]),
    relatedArticles: Object.freeze(["help/dashboard/overview", "help/rbac/missing-action", "help/start/first-login"]),
    captureIds: [],
    captureStatus: "guide-only",
    sourceGuide: "both",
    popular: true,
    navigate: null,
  },
  {
    id: "help/start/school-setup",
    title: "Configuration initiale de l’établissement",
    summary:
      "L’assistant ouvre les écrans déjà existants. Il s’adresse à l’administrateur d’établissement. Mobile n’ouvre pas l’assistant tout seul après connexion.",
    category: HELP_CATEGORY.DEMARRAGE,
    order: 30,
    roles: SCHOOL_SETTINGS_ROLES,
    permissions: Object.freeze(["Paramètres Établissement:READ"]),
    platforms: BOTH,
    routeKeys: Object.freeze([
      HELP_SCREEN.SETTINGS_SETUP,
      HELP_SCREEN.SETTINGS,
      HELP_SCREEN.DASHBOARD,
    ]),
    keywords: Object.freeze([
      "configuration initiale",
      "assistant de configuration",
      "configuration de l’établissement",
      "année scolaire",
      "structure pédagogique",
    ]),
    steps: Object.freeze([
      "Ouvrez Paramètres → Configuration de l’établissement (Web et Mobile).",
      "L’écran affiche Assistant de configuration. Les actions ouvrent les écrans existants : aucun formulaire n’est dupliqué ici.",
      "Parcours essentiel : Année scolaire, puis Structure pédagogique, puis Classes. Comptes utilisateurs peut être ouvert à tout moment.",
      "Si une étape affiche Étape précédente requise, terminez d’abord l’étape précédente. Utilisez Ouvrir → ou Revoir →.",
      "Plus tard reporte l’assistant pour la session en cours. Sur le Web, si la configuration n’a pas démarré, l’administrateur d’établissement peut être redirigé ici après le changement de mot de passe.",
      "Mobile : ouvrez l’assistant depuis Paramètres ou depuis Configuration rapide. Il n’existe pas d’ouverture automatique après Se connecter.",
    ]),
    relatedArticles: Object.freeze([
      "help/start/quick-config",
      "help/settings/academic-year",
      "help/settings/pedagogical-structure",
      "help/classes/create",
      "help/users/create",
    ]),
    captureIds: [],
    captureStatus: "guide-only",
    sourceGuide: "both",
    popular: true,
    navigate: nav("/parametres/configuration-etablissement", "SchoolSetup", "Paramètres Établissement:READ"),
  },
  {
    id: "help/start/quick-config",
    title: "Configuration rapide",
    summary:
      "Le widget Configuration rapide rappelle la progression (X / 3) tant que la configuration essentielle n’est pas terminée.",
    category: HELP_CATEGORY.DEMARRAGE,
    order: 40,
    roles: SCHOOL_SETTINGS_ROLES,
    permissions: Object.freeze(["Paramètres Établissement:READ"]),
    platforms: BOTH,
    routeKeys: Object.freeze([HELP_SCREEN.DASHBOARD, HELP_SCREEN.SETTINGS_SETUP]),
    keywords: Object.freeze(["configuration rapide", "continuer", "widget", "scolarité"]),
    steps: Object.freeze([
      "Sur le Web, le widget Configuration rapide apparaît dans Scolarité (Mon établissement) tant que le statut est à démarrer ou en cours.",
      "Sur Mobile, le même widget se trouve dans le hub Scolarité.",
      "Appuyez ou cliquez sur Continuer pour ouvrir l’assistant. Les libellés d’étape sont Année scolaire, Structure pédagogique, Classes et Comptes utilisateurs.",
      "La section Complétude recommandée liste Périodes scolaires, Enseignants, Élèves, Grilles tarifaires et Notifications, avec Configuré ou À compléter. Ce n’est pas un blocage de l’assistant.",
    ]),
    relatedArticles: Object.freeze(["help/start/school-setup", "help/dashboard/overview"]),
    captureIds: [],
    captureStatus: "guide-only",
    sourceGuide: "both",
    popular: false,
    navigate: nav("/parametres/configuration-etablissement", "SchoolSetup", "Paramètres Établissement:READ"),
  },
  {
    id: "help/classes/head-teacher",
    title: "Consulter le professeur principal",
    summary: "Chaque classe active peut afficher un professeur principal. Non assigné signifie qu’aucun enseignant n’est encore affecté.",
    category: HELP_CATEGORY.SCOLARITE,
    order: 40,
    roles: SCHOOL_STAFF_ROLES,
    permissions: Object.freeze(["Classes:READ"]),
    platforms: BOTH,
    routeKeys: Object.freeze([HELP_SCREEN.CLASSES]),
    keywords: Object.freeze(["professeur principal", "professeur", "titulaire", "classe", "non assigné"]),
    steps: Object.freeze([
      "Ouvrez Mon établissement → Classes (Web) ou Classes (Mobile).",
      "La ligne Professeur principal : affiche le nom, ou Non assigné.",
      "L’action Affecter un professeur principal n’apparaît que si votre rôle peut modifier les classes ou les affectations.",
    ]),
    relatedArticles: Object.freeze(["help/classes/head-teacher-assign", "help/classes/list", "help/teachers/list"]),
    captureIds: [],
    captureStatus: "guide-only",
    sourceGuide: "both",
    popular: true,
    navigate: nav("/etablissement/classes", "Classes", "Classes:READ"),
  },
  {
    id: "help/classes/head-teacher-assign",
    title: "Affecter un professeur principal",
    summary: "L’affectation n’apparaît que si Classes:UPDATE ou un droit d’affectation est accordé. Un enseignant ne peut être professeur principal que d’une classe active à la fois dans ce parcours.",
    category: HELP_CATEGORY.SCOLARITE,
    order: 50,
    roles: ESTABLISHMENT_ADMIN_ROLES,
    permissions: Object.freeze(["Classes:UPDATE"]),
    platforms: BOTH,
    routeKeys: Object.freeze([HELP_SCREEN.CLASSES]),
    keywords: Object.freeze([
      "affecter un professeur principal",
      "modifier l'affectation",
      "retirer l'affectation",
      "professeur principal",
    ]),
    steps: Object.freeze([
      "Ouvrez Classes. Sur une classe active, utilisez Affecter un professeur principal, ou Modifier l'affectation s’il y en a déjà un.",
      "Recherchez un enseignant, puis Confirmer l'affectation. Annuler ferme sans enregistrer.",
      "Retirer l'affectation enlève le professeur principal : la classe affiche alors Non assigné.",
    ]),
    relatedArticles: Object.freeze(["help/classes/head-teacher", "help/teachers/list"]),
    captureIds: [],
    captureStatus: "guide-only",
    sourceGuide: "both",
    popular: false,
    navigate: nav("/etablissement/classes", "Classes", "Classes:UPDATE"),
  },
  {
    id: "help/students/mobile-record",
    title: "Fiche élève (Mobile)",
    summary: "Sur Mobile, la fiche s’ouvre depuis la liste des élèves. Les sous-écrans Notes, Présences et Paiements dépendent des droits.",
    category: HELP_CATEGORY.SCOLARITE,
    order: 30,
    roles: SCHOOL_STAFF_ROLES,
    permissions: Object.freeze(["Élèves:READ"]),
    platforms: Object.freeze([MOBILE]),
    routeKeys: Object.freeze([HELP_SCREEN.STUDENTS]),
    keywords: Object.freeze(["fiche élève", "élève", "dossier", "mobile"]),
    steps: Object.freeze([
      "Ouvrez Élèves, puis appuyez sur la ligne de l’élève.",
      "L’écran Fiche élève affiche l’identité et les raccourcis autorisés.",
      "L’inscription d’un nouvel élève se fait depuis une classe, pas depuis un bouton global d’ajout.",
    ]),
    relatedArticles: Object.freeze(["help/students/directory", "help/students/enroll"]),
    captureIds: [],
    captureStatus: "guide-only",
    sourceGuide: "mobile",
    popular: false,
    navigate: nav(null, "Students", "Élèves:READ"),
  },
  {
    id: "help/report-cards/consult",
    title: "Consulter les bulletins",
    summary:
      "Les bulletins publiés se consultent dans Bulletins. Cette aide ne décrit pas un parcours d’édition de modèle ni une publication garantie pour tous les établissements.",
    category: HELP_CATEGORY.PEDAGOGIE,
    order: 40,
    roles: Object.freeze([
      ...SCHOOL_STAFF_ROLES.filter((role) => role !== HELP_ROLE.ACCOUNTANT),
      HELP_ROLE.PARENT,
      HELP_ROLE.STUDENT,
    ]),
    permissions: Object.freeze(["Bulletins:READ"]),
    platforms: BOTH,
    routeKeys: Object.freeze([HELP_SCREEN.REPORT_CARDS, HELP_SCREEN.DASHBOARD, HELP_SCREEN.PARENT_HOME, HELP_SCREEN.STUDENT_HOME]),
    keywords: Object.freeze(["bulletin", "bulletins", "relevé", "publication"]),
    steps: Object.freeze([
      "Ouvrez Bulletins lorsque l’entrée est visible (Web : Pédagogie → Bulletins ; Mobile : menu Bulletins / Mes bulletins).",
      "Consultez uniquement les publications de votre périmètre. Un parent ou un élève ne voit que ses bulletins.",
      "Si aucune publication n’apparaît, l’établissement n’a pas encore publié de bulletin pour cette période, ou votre rôle n’y a pas accès.",
    ]),
    relatedArticles: Object.freeze(["help/grades/evaluations", "help/settings/academic-periods"]),
    captureIds: [],
    captureStatus: "guide-only",
    sourceGuide: "both",
    popular: true,
    navigate: nav("/bulletins", "ReportCards", "Bulletins:READ"),
  },
  {
    id: "help/payments/unpaid",
    title: "Consulter les impayés",
    summary:
      "L’écran Impayés affiche le reste à payer. Les montants d’exemple de cette aide sont fictifs (ils ne correspondent à aucun élève réel).",
    category: HELP_CATEGORY.FINANCE,
    order: 30,
    roles: Object.freeze([
      HELP_ROLE.SCHOOL_ADMIN,
      HELP_ROLE.PRINCIPAL,
      HELP_ROLE.PROVISEUR,
      HELP_ROLE.SECRETARY,
      HELP_ROLE.ACCOUNTANT,
    ]),
    permissions: Object.freeze(["Impayés:READ"]),
    platforms: BOTH,
    routeKeys: Object.freeze([HELP_SCREEN.PAYMENTS]),
    keywords: Object.freeze(["impayés", "restant", "payé", "frais", "situation financière", "total restant"]),
    steps: Object.freeze([
      "Ouvrez Finances → Impayés (Web) ou Impayés (Mobile) lorsque l’entrée est visible.",
      "Le libellé Total restant indique le solde encore dû, pas un encaissement.",
      "Les statuts d’obligation peuvent afficher Payé ou Partiellement payé selon les données chargées.",
      "Exemple fictif : un reste de 15 000 n’est qu’une illustration. Vérifiez toujours les montants affichés pour l’élève concerné.",
      "L’enregistrement d’un paiement se fait depuis Paiements, pas depuis un bouton d’ajout d’élève.",
    ]),
    relatedArticles: Object.freeze(["help/payments/overview", "help/payments/record"]),
    captureIds: [],
    captureStatus: "guide-only",
    sourceGuide: "both",
    popular: true,
    navigate: nav("/finances/impayes", "Unpaid", "Impayés:READ"),
  },
  {
    id: "help/settings/notifications",
    title: "Consulter les notifications de l’établissement",
    summary:
      "Paramètres → Notifications affiche quels événements informent les familles, les élèves, les enseignants et l’administration, et par quels canaux.",
    category: HELP_CATEGORY.COMMUNICATION,
    order: 40,
    roles: SCHOOL_SETTINGS_ROLES,
    permissions: Object.freeze(["Paramètres Établissement:READ"]),
    platforms: Object.freeze([WEB]),
    routeKeys: Object.freeze([HELP_SCREEN.SETTINGS_NOTIFICATIONS, HELP_SCREEN.SETTINGS]),
    keywords: Object.freeze(["notifications", "événements", "canaux", "push", "e-mail", "application"]),
    steps: Object.freeze([
      "Ouvrez Paramètres → Notifications. La carte du hub porte le badge Disponible.",
      "Le tableau liste l’événement, les destinataires (Parents, Élèves, Enseignants, Administration) et les canaux Application, Push et E-mail.",
      "Sans droit de modification, les interrupteurs restent en lecture. La réception d’une notification in-app n’équivaut pas à configurer cet écran.",
      "Les notifications push appareil ne sont opérationnelles que sur l’application Mobile Android native, pas dans Expo Go ni sur le Web.",
    ]),
    relatedArticles: Object.freeze([
      "help/settings/notifications-edit",
      "help/communication/notifications",
      "help/settings/coming-soon",
    ]),
    captureIds: [],
    captureStatus: "guide-only",
    sourceGuide: "web",
    popular: true,
    navigate: nav("/parametres/notifications", null, "Paramètres Établissement:READ"),
  },
  {
    id: "help/settings/notifications-edit",
    title: "Modifier les notifications de l’établissement",
    summary: "La modification n’apparaît que si Paramètres Établissement:UPDATE est accordé. Chaque interrupteur est envoyé immédiatement.",
    category: HELP_CATEGORY.COMMUNICATION,
    order: 50,
    roles: SCHOOL_SETTINGS_ROLES,
    permissions: Object.freeze(["Paramètres Établissement:UPDATE"]),
    platforms: Object.freeze([WEB]),
    routeKeys: Object.freeze([HELP_SCREEN.SETTINGS_NOTIFICATIONS]),
    keywords: Object.freeze(["notifications", "interrupteur", "push", "e-mail", "application"]),
    steps: Object.freeze([
      "Ouvrez Paramètres → Notifications.",
      "Lorsque les interrupteurs sont actifs, choisissez le canal Application, Push ou E-mail pour chaque événement et destinataire.",
      "Il n’y a pas de bouton Enregistrer sur cet écran : le changement part dès que vous actionnez l’interrupteur.",
    ]),
    relatedArticles: Object.freeze(["help/settings/notifications"]),
    captureIds: [],
    captureStatus: "guide-only",
    sourceGuide: "web",
    popular: false,
    navigate: nav("/parametres/notifications", null, "Paramètres Établissement:UPDATE"),
  },
  {
    id: "help/account/password",
    title: "Mot de passe et identifiants",
    summary:
      "Le changement de mot de passe à la première connexion est obligatoire si Somafrik affiche Nouveau mot de passe. La réinitialisation pour un autre compte est une action administrateur.",
    category: HELP_CATEGORY.COMPTE,
    order: 10,
    roles: AUTHENTICATED_HELP_ROLES,
    permissions: [],
    platforms: BOTH,
    routeKeys: Object.freeze([HELP_SCREEN.USERS, HELP_SCREEN.DASHBOARD, HELP_SCREEN.SETTINGS_SECURITY]),
    keywords: Object.freeze(["mot de passe", "réinitialiser", "identifiants", "pin", "nouveau mot de passe"]),
    steps: Object.freeze([
      "À la première connexion, la fenêtre Nouveau mot de passe demande un mot de passe et une Confirmation (Web : Enregistrer ; Mobile : Valider).",
      "Il n’existe pas de lien « mot de passe oublié » sur l’écran de connexion.",
      "Un administrateur habilité ouvre Comptes utilisateurs puis Réinitialiser le mot de passe sur la ligne du compte.",
      "Ne publiez jamais un mot de passe temporaire dans un groupe de discussion.",
    ]),
    relatedArticles: Object.freeze(["help/start/first-login", "help/users/list", "help/account/logout"]),
    captureIds: [],
    captureStatus: "guide-only",
    sourceGuide: "both",
    popular: true,
    navigate: null,
  },
  {
    id: "help/account/logout",
    title: "Se déconnecter",
    summary: "La déconnexion ferme la session de cet appareil. Elle ne supprime pas le compte.",
    category: HELP_CATEGORY.COMPTE,
    order: 20,
    roles: AUTHENTICATED_HELP_ROLES,
    permissions: [],
    platforms: BOTH,
    routeKeys: Object.freeze([HELP_SCREEN.DASHBOARD, HELP_SCREEN.PARENT_HOME, HELP_SCREEN.STUDENT_HOME, HELP_SCREEN.SETTINGS]),
    keywords: Object.freeze(["déconnexion", "se déconnecter", "session", "fermer"]),
    steps: Object.freeze([
      "Web : utilisez Déconnexion dans la barre supérieure.",
      "Mobile : ouvrez le menu, puis Déconnexion.",
      "Après déconnexion, Somafrik affiche l’écran de connexion (Web) ou l’accueil Welcome (Mobile).",
    ]),
    relatedArticles: Object.freeze(["help/account/password", "help/account/privacy"]),
    captureIds: [],
    captureStatus: "guide-only",
    sourceGuide: "both",
    popular: false,
    navigate: null,
  },
  {
    id: "help/account/privacy",
    title: "Confidentialité et suppression de compte",
    summary:
      "La politique de confidentialité et la demande de suppression de compte sont des pages légales Somafrik, distinctes de l’aide métier.",
    category: HELP_CATEGORY.COMPTE,
    order: 30,
    roles: AUTHENTICATED_HELP_ROLES,
    permissions: [],
    platforms: BOTH,
    routeKeys: Object.freeze([HELP_SCREEN.DASHBOARD, HELP_SCREEN.PARENT_HOME, HELP_SCREEN.STUDENT_HOME]),
    keywords: Object.freeze(["confidentialité", "suppression de compte", "rgpd", "vie privée"]),
    steps: Object.freeze([
      "Web : les pages Politique de confidentialité (/confidentialite) et Suppression de compte (/suppression-compte) sont accessibles depuis le site Somafrik.",
      "Mobile : le menu propose Politique de confidentialité et Demander la suppression de mon compte. Ces liens ouvrent les pages légales du site.",
      "La suppression n’est pas une action immédiate dans l’application métier : suivez le formulaire publié sur la page légale.",
    ]),
    relatedArticles: Object.freeze(["help/account/logout", "help/assistance/contact"]),
    captureIds: [],
    captureStatus: "guide-only",
    sourceGuide: "both",
    popular: false,
    navigate: null,
  },
  {
    id: "help/assistance/contact",
    title: "Je n’ai pas trouvé la réponse",
    summary:
      "L’aide produit n’ouvre pas de ticket vers Somafrik. Pour un compte, un paiement ou un dossier, contactez l’administration de votre établissement.",
    category: HELP_CATEGORY.ASSISTANCE,
    order: 10,
    roles: AUTHENTICATED_HELP_ROLES,
    permissions: [],
    platforms: BOTH,
    routeKeys: Object.freeze(Object.values(HELP_SCREEN)),
    keywords: Object.freeze(["aide", "assistance", "support", "administration", "réponse", "contact"]),
    steps: Object.freeze([
      "Relancez une recherche dans l’aide (élève, paiement, présence, classe, mot de passe, bulletin, message).",
      "Si l’action métier manque, vérifiez d’abord votre rôle : un bouton absent n’est pas forcément une anomalie.",
      "Pour une correction de compte, de paiement ou de dossier, adressez-vous à l’administration de votre établissement.",
      "Sur Mobile, l’écran Support oriente vers cette même administration. Ce n’est pas le catalogue d’aide.",
      "Les pages légales (confidentialité, suppression de compte) restent sur le site Somafrik ; elles ne remplacent pas l’administration de l’école.",
    ]),
    relatedArticles: Object.freeze(["help/rbac/missing-action", "help/start/navigation"]),
    captureIds: [],
    captureStatus: "guide-only",
    sourceGuide: "both",
    popular: false,
    navigate: null,
  },
];
