import {
  AUTHENTICATED_HELP_ROLES,
  ESTABLISHMENT_ADMIN_ROLES,
  SCHOOL_SETTINGS_ROLES,
  HELP_PLATFORM,
  HELP_ROLE,
  HELP_SCREEN,
  SCHOOL_STAFF_ROLES,
} from "./constants.js";
import { freezeCatalog } from "./freeze.js";

const WEB = HELP_PLATFORM.WEB;
const MOBILE = HELP_PLATFORM.MOBILE;

const BOTH = Object.freeze([WEB, MOBILE]);

function nav(webPath, mobileRoute, permission) {
  return { webPath, mobileRoute, permission };
}

const ARTICLES = [
  {
    id: "help/rbac/missing-action",
    title: "Je ne vois pas un bouton",
    summary:
      "Somafrik masque les actions selon le rôle et les permissions effectives. Un bouton absent n’est pas forcément une anomalie.",
    roles: AUTHENTICATED_HELP_ROLES,
    permissions: [],
    platforms: BOTH,
    routeKeys: Object.freeze(
      Object.values(HELP_SCREEN).filter((screen) => !String(screen).startsWith("settings-")),
    ),
    keywords: Object.freeze(["bouton", "permission", "droit", "rbac", "manque", "ajouter", "modifier"]),
    steps: Object.freeze([
      "Vérifiez d’abord votre rôle et vos permissions.",
      "Si la consultation fonctionne mais qu’Ajouter, Modifier, Archiver, Supprimer, Affecter ou Enregistrer n’apparaît pas, votre compte peut ne pas disposer de cette action.",
      "Demandez à un administrateur habilité de vérifier votre rôle ou vos droits.",
      "Ne cherchez pas à contourner un bouton absent.",
    ]),
    relatedArticles: Object.freeze(["help/dashboard/overview"]),
    captureIds: [],
    captureStatus: "guide-only",
    sourceGuide: "both",
    popular: true,
    navigate: null,
  },
  {
    id: "help/dashboard/overview",
    title: "Tableau de bord",
    summary:
      "Le tableau de bord est le point d’entrée de pilotage. Les indicateurs dépendent du rôle et du périmètre de l’utilisateur.",
    roles: SCHOOL_STAFF_ROLES,
    permissions: [],
    platforms: BOTH,
    routeKeys: Object.freeze([HELP_SCREEN.DASHBOARD]),
    keywords: Object.freeze(["tableau de bord", "accueil", "indicateurs", "pilotage"]),
    steps: Object.freeze([
      "Après connexion, Somafrik affiche uniquement les modules autorisés pour votre rôle.",
      "Utilisez le tableau de bord pour rejoindre les modules disponibles.",
      "Les indicateurs viennent du runtime ; le périmètre affiché est le code interne de l’établissement, distinct du code public saisi à la connexion.",
    ]),
    relatedArticles: Object.freeze(["help/rbac/missing-action", "help/classes/list"]),
    captureIds: Object.freeze(["W02"]),
    captureStatus: "validated",
    sourceGuide: "both",
    popular: true,
    navigate: nav("/tableau-de-bord", "Home", null),
  },
  {
    id: "help/classes/list",
    title: "Consulter les classes",
    summary: "Ouvrez Classes pour rechercher, filtrer et consulter la liste des classes de l’établissement.",
    roles: SCHOOL_STAFF_ROLES,
    permissions: Object.freeze(["Classes:READ"]),
    platforms: BOTH,
    routeKeys: Object.freeze([HELP_SCREEN.CLASSES, HELP_SCREEN.DASHBOARD]),
    keywords: Object.freeze(["classes", "liste", "rechercher", "statut", "effectif"]),
    steps: Object.freeze([
      "Ouvrez Mon établissement → Classes (Web) ou Classes (Mobile).",
      "Utilisez la recherche pour retrouver une classe par nom ou code.",
      "Sur le Web, le filtre Tous les statuts / Actives / Inactives restreint la liste ; Actualiser recharge les données.",
      "Sur Mobile, l’écran affiche les classes actives, les élèves inscrits et le taux de présence lorsqu’il est connu.",
    ]),
    relatedArticles: Object.freeze(["help/classes/create", "help/students/directory"]),
    captureIds: Object.freeze(["W03", "M02"]),
    captureStatus: "validated",
    sourceGuide: "both",
    popular: true,
    navigate: nav("/etablissement/classes", "Classes", "Classes:READ"),
  },
  {
    id: "help/classes/create",
    title: "Créer une classe",
    summary:
      "La création d’une classe n’apparaît que si votre rôle possède le droit de création. Vérifiez les valeurs présélectionnées avant d’enregistrer.",
    roles: ESTABLISHMENT_ADMIN_ROLES,
    permissions: Object.freeze(["Classes:CREATE"]),
    platforms: BOTH,
    routeKeys: Object.freeze([HELP_SCREEN.CLASSES]),
    keywords: Object.freeze(["créer", "ajouter", "classe", "année", "niveau", "groupe"]),
    steps: Object.freeze([
      "Si l’action Ajouter (Web) ou Créer une classe (Mobile) est visible, ouvrez-la.",
      "Vérifiez l’année scolaire.",
      "Choisissez le niveau, l’orientation pédagogique si elle s’applique, puis le groupe demandé par l’interface.",
      "Les valeurs proposées proviennent du référentiel pédagogique actif : une présélection n’est pas une recommandation métier.",
      "Enregistrez uniquement après vérification. Une année scolaire doit être configurée dans Paramètres (Web et Mobile) avant de pouvoir créer les classes.",
    ]),
    relatedArticles: Object.freeze(["help/classes/list", "help/settings/academic-year"]),
    captureIds: Object.freeze(["W04", "M03"]),
    captureStatus: "validated",
    sourceGuide: "both",
    popular: false,
    navigate: nav("/etablissement/classes", "Classes", "Classes:CREATE"),
  },
  {
    id: "help/students/directory",
    title: "Annuaire Élèves",
    summary: "L’annuaire permet de rechercher un élève. Il ne contient pas de bouton général « Ajouter un élève ».",
    roles: SCHOOL_STAFF_ROLES,
    permissions: Object.freeze(["Élèves:READ"]),
    platforms: BOTH,
    routeKeys: Object.freeze([HELP_SCREEN.STUDENTS, HELP_SCREEN.CLASSES]),
    keywords: Object.freeze(["élèves", "annuaire", "matricule", "dossier", "recherche"]),
    steps: Object.freeze([
      "Ouvrez Mon établissement → Élèves (Web) ou Élèves (Mobile).",
      "Recherchez par nom, prénom, matricule, identifiant ou classe.",
      "Sur le Web, cliquez sur Dossier pour ouvrir l’espace de l’élève.",
      "Sur Mobile, appuyez sur la ligne d’un élève pour ouvrir sa fiche si votre rôle le permet.",
      "L’inscription d’un nouvel élève se fait depuis une classe, pas depuis un bouton global d’ajout.",
    ]),
    relatedArticles: Object.freeze(["help/students/enroll", "help/students/record"]),
    captureIds: Object.freeze(["W05", "M04"]),
    captureStatus: "validated",
    sourceGuide: "both",
    popular: true,
    navigate: nav("/etablissement/eleves", "Students", "Élèves:READ"),
  },
  {
    id: "help/students/enroll",
    title: "Inscrire un élève",
    summary: "L’inscription rattache un élève à une classe. L’action n’apparaît que si Élèves:CREATE est accordé.",
    roles: ESTABLISHMENT_ADMIN_ROLES,
    permissions: Object.freeze(["Élèves:CREATE"]),
    platforms: BOTH,
    routeKeys: Object.freeze([HELP_SCREEN.STUDENTS, HELP_SCREEN.CLASSES]),
    keywords: Object.freeze(["inscrire", "élève", "classe", "identifiants", "création"]),
    steps: Object.freeze([
      "Ouvrez une classe puis utilisez Inscrire un élève lorsque l’action est visible.",
      "Sur le Web : Mon établissement → Classes → Élèves de la classe → Inscrire un élève.",
      "Sur Mobile : choisissez la classe, saisissez le prénom et le nom, renseignez éventuellement le téléphone du parent, puis enregistrez.",
      "Après une inscription réussie sur Mobile, Somafrik ouvre Remettre les identifiants élève. Transmettez-les par un canal sûr avant de fermer la fenêtre.",
      "Ne publiez jamais un secret temporaire dans un groupe de discussion.",
    ]),
    relatedArticles: Object.freeze(["help/students/directory", "help/classes/list"]),
    captureIds: Object.freeze(["M05", "M06"]),
    captureStatus: "validated",
    sourceGuide: "both",
    popular: false,
    navigate: nav("/etablissement/classes", "Students", "Élèves:CREATE"),
  },
  {
    id: "help/students/record",
    title: "Dossier élève",
    summary: "Le dossier affiche les sections autorisées au rôle. L’archivage n’est pas une suppression physique.",
    roles: SCHOOL_STAFF_ROLES,
    permissions: Object.freeze(["Élèves:READ"]),
    platforms: Object.freeze([WEB]),
    routeKeys: Object.freeze([HELP_SCREEN.STUDENTS]),
    keywords: Object.freeze(["dossier", "élève", "archiver", "fiche"]),
    steps: Object.freeze([
      "Depuis l’annuaire Élèves, cliquez sur Dossier.",
      "Seules les sections autorisées au rôle sont visibles.",
      "Si votre rôle possède le droit correspondant, Archiver retire l’élève de l’annuaire actif.",
    ]),
    relatedArticles: Object.freeze(["help/students/directory"]),
    captureIds: Object.freeze(["W06"]),
    captureStatus: "validated",
    sourceGuide: "web",
    popular: false,
    navigate: nav("/etablissement/eleves", null, "Élèves:READ"),
  },
  {
    id: "help/teachers/list",
    title: "Consulter les enseignants",
    summary: "La liste enseignants affiche l’identité, les affectations et le statut selon les droits de la session.",
    roles: SCHOOL_STAFF_ROLES.filter((role) => role !== HELP_ROLE.TEACHER && role !== HELP_ROLE.ACCOUNTANT),
    permissions: Object.freeze(["Enseignants:READ"]),
    platforms: BOTH,
    routeKeys: Object.freeze([HELP_SCREEN.TEACHERS]),
    keywords: Object.freeze(["enseignants", "liste", "affectations", "spécialité"]),
    steps: Object.freeze([
      "Ouvrez Mon établissement → Enseignants (Web) ou Enseignants (Mobile).",
      "Consultez l’identité, l’identifiant enseignant, le contact, la spécialité et les affectations lorsqu’ils sont affichés.",
      "Les actions Modifier, Affecter ou Archiver n’apparaissent que si votre rôle les possède.",
    ]),
    relatedArticles: Object.freeze(["help/teachers/web-identity-from-users", "help/teachers/mobile-create"]),
    captureIds: Object.freeze(["M07"]),
    captureStatus: "guide-only",
    sourceGuide: "both",
    popular: false,
    navigate: nav("/etablissement/enseignants", "Teachers", "Enseignants:READ"),
  },
  {
    id: "help/teachers/web-identity-from-users",
    title: "Créer l’identité d’un enseignant (Web)",
    summary:
      "Sur le Web, l’écran Enseignants n’est pas le point de création d’identité. La création se fait depuis Comptes utilisateurs.",
    roles: ESTABLISHMENT_ADMIN_ROLES,
    permissions: Object.freeze(["Utilisateurs:CREATE"]),
    platforms: Object.freeze([WEB]),
    routeKeys: Object.freeze([HELP_SCREEN.TEACHERS, HELP_SCREEN.USERS]),
    keywords: Object.freeze(["enseignant", "créer", "utilisateurs", "identité", "web"]),
    steps: Object.freeze([
      "Ouvrez Mon établissement → Comptes utilisateurs.",
      "Créez l’identité utilisateur (aucun rôle n’est attribué à la création côté établissement).",
      "Utilisez ensuite Attribuer pour accorder le rôle Enseignant, uniquement si votre compte est autorisé à l’accorder.",
      "Ne cherchez pas un bouton de création d’identité sur l’écran Enseignants Web.",
    ]),
    relatedArticles: Object.freeze(["help/users/create", "help/users/assign-role", "help/teachers/list"]),
    captureIds: [],
    captureStatus: "guide-only",
    sourceGuide: "web",
    popular: false,
    navigate: nav("/etablissement/comptes-utilisateurs", null, "Utilisateurs:CREATE"),
  },
  {
    id: "help/teachers/mobile-create",
    title: "Créer un enseignant (Mobile)",
    summary:
      "Lorsque Créer un enseignant est visible, Mobile utilise le workflow canonique de création d’identité enseignant.",
    roles: ESTABLISHMENT_ADMIN_ROLES,
    permissions: Object.freeze(["Enseignants:CREATE"]),
    platforms: Object.freeze([MOBILE]),
    routeKeys: Object.freeze([HELP_SCREEN.TEACHERS]),
    keywords: Object.freeze(["enseignant", "créer", "mobile", "identifiants"]),
    steps: Object.freeze([
      "Si Créer un enseignant est visible, ouvrez l’action.",
      "Saisissez le prénom et le nom, puis éventuellement téléphone, e-mail et date de naissance.",
      "Saisissez le mot de passe temporaire, enregistrez, puis remettez les identifiants depuis la fenêtre prévue.",
      "La modification de la matrice des droits reste une fonction Web.",
    ]),
    relatedArticles: Object.freeze(["help/teachers/list", "help/users/create"]),
    captureIds: Object.freeze(["M08"]),
    captureStatus: "validated",
    sourceGuide: "mobile",
    popular: false,
    navigate: nav(null, "Teachers", "Enseignants:CREATE"),
  },
  {
    id: "help/teachers/assign-course",
    title: "Affecter un cours à un enseignant",
    summary: "L’affectation d’un cours n’apparaît que si votre rôle possède le droit sur les affectations.",
    roles: ESTABLISHMENT_ADMIN_ROLES,
    permissions: Object.freeze(["Affectations:CREATE"]),
    platforms: BOTH,
    routeKeys: Object.freeze([HELP_SCREEN.TEACHERS]),
    keywords: Object.freeze(["affecter", "cours", "matière", "classe", "enseignant"]),
    steps: Object.freeze([
      "Depuis la liste Enseignants, ouvrez Affecter un cours lorsque l’action est visible.",
      "Choisissez une classe active puis un cours/matière disponible.",
      "Enregistrez l’affectation. Les listes proviennent des données canoniques de l’établissement.",
    ]),
    relatedArticles: Object.freeze(["help/teachers/list"]),
    captureIds: [],
    captureStatus: "guide-only",
    sourceGuide: "both",
    popular: false,
    navigate: nav("/etablissement/enseignants", "Teachers", "Affectations:CREATE"),
  },
  {
    id: "help/users/list",
    title: "Comptes utilisateurs",
    summary: "Un compte Somafrik contient une identité et peut recevoir un ou plusieurs rôles actifs.",
    roles: ESTABLISHMENT_ADMIN_ROLES,
    permissions: Object.freeze(["Utilisateurs:READ"]),
    platforms: BOTH,
    routeKeys: Object.freeze([HELP_SCREEN.USERS]),
    keywords: Object.freeze(["utilisateurs", "comptes", "rôles", "identité"]),
    steps: Object.freeze([
      "Ouvrez Mon établissement → Comptes utilisateurs (Web) ou Utilisateurs (Mobile).",
      "Identité utilisateur et rôle sont deux notions distinctes.",
      "Selon vos permissions, vous pouvez consulter la fiche, modifier l’identité, attribuer des rôles, suspendre un compte ou réinitialiser un mot de passe.",
      "La matrice globale des droits par rôle se gère sur le Web ; elle n’est pas modifiable depuis le Mobile.",
    ]),
    relatedArticles: Object.freeze(["help/users/create", "help/users/assign-role", "help/rbac/missing-action"]),
    captureIds: Object.freeze(["M09"]),
    captureStatus: "guide-only",
    sourceGuide: "both",
    popular: false,
    navigate: nav("/etablissement/comptes-utilisateurs", "Users", "Utilisateurs:READ"),
  },
  {
    id: "help/users/create",
    title: "Créer un utilisateur",
    summary:
      "Côté établissement, la création d’un compte enregistre l’identité sans rôle. L’attribution du rôle se fait ensuite via Attribuer.",
    roles: ESTABLISHMENT_ADMIN_ROLES,
    permissions: Object.freeze(["Utilisateurs:CREATE"]),
    platforms: BOTH,
    routeKeys: Object.freeze([HELP_SCREEN.USERS]),
    keywords: Object.freeze(["créer", "utilisateur", "compte", "mot de passe temporaire", "identité", "attribuer"]),
    steps: Object.freeze([
      "Ouvrez Mon établissement → Comptes utilisateurs.",
      "Ouvrez Nouvel utilisateur lorsque l’action est visible.",
      "Renseignez l’identité : prénom, nom, puis téléphone et e-mail selon le formulaire.",
      "Un identifiant de connexion est généré côté serveur. Définissez le mot de passe temporaire selon le workflow affiché.",
      "Enregistrez le compte. Côté établissement, aucun rôle n’est attribué pendant cette création.",
      "Utilisez ensuite Attribuer pour choisir un rôle déjà autorisé du catalogue.",
      "La création d’un utilisateur ne modifie jamais la matrice globale des droits.",
      "Sur Mobile, remettez les identifiants depuis Remettre les identifiants utilisateur.",
    ]),
    relatedArticles: Object.freeze(["help/users/list", "help/users/assign-role", "help/teachers/web-identity-from-users"]),
    captureIds: Object.freeze(["M10"]),
    captureStatus: "guide-only",
    sourceGuide: "both",
    popular: false,
    navigate: nav("/etablissement/comptes-utilisateurs", "Users", "Utilisateurs:CREATE"),
  },
  {
    id: "help/users/assign-role",
    title: "Attribuer un rôle à un utilisateur",
    summary:
      "L’identité, le compte et le rôle sont distincts. L’attribution d’un rôle existant ne modifie pas la matrice globale des droits.",
    roles: ESTABLISHMENT_ADMIN_ROLES,
    permissions: Object.freeze(["Utilisateurs:UPDATE"]),
    platforms: BOTH,
    routeKeys: Object.freeze([HELP_SCREEN.USERS, HELP_SCREEN.SETTINGS_ROLES]),
    keywords: Object.freeze(["attribuer", "rôle", "compte", "permissions", "identité"]),
    steps: Object.freeze([
      "Identité : prénom, nom et contacts de la personne.",
      "Compte : identifiant de connexion généré par Somafrik.",
      "Rôle : ensemble de permissions du catalogue. Les permissions d’un rôle sont définies par le Super administrateur.",
      "Ouvrez Mon établissement → Comptes utilisateurs.",
      "Sur la ligne du compte, ouvrez Attribuer lorsque l’action est visible.",
      "Choisissez un rôle déjà autorisé pour votre établissement, puis enregistrez.",
      "Un administrateur d’établissement ne modifie pas la matrice CRUD depuis Paramètres → Rôles et droits.",
    ]),
    relatedArticles: Object.freeze(["help/users/create", "help/users/list", "help/settings/roles-permissions"]),
    captureIds: [],
    captureStatus: "guide-only",
    sourceGuide: "both",
    popular: false,
    navigate: nav("/etablissement/comptes-utilisateurs", "Users", "Utilisateurs:UPDATE"),
  },
  {
    id: "help/attendance/choose-class",
    title: "Choisir une classe pour l’appel",
    summary: "L’écran Présences commence par le choix d’une classe du périmètre autorisé.",
    roles: SCHOOL_STAFF_ROLES,
    permissions: Object.freeze(["Présences:READ"]),
    platforms: BOTH,
    routeKeys: Object.freeze([HELP_SCREEN.ATTENDANCE, HELP_SCREEN.DASHBOARD]),
    keywords: Object.freeze(["présences", "appel", "classes", "roster"]),
    steps: Object.freeze([
      "Ouvrez Présences (Web) ou Présences / Appel (Mobile).",
      "Choisissez une classe dans votre périmètre. Un enseignant ne voit pas automatiquement l’annuaire admin d’une classe homonyme.",
      "Vérifiez la date et la classe affichées avant toute saisie.",
      "Un utilisateur sans droit de modification peut consulter l’écran sans obtenir les actions d’écriture.",
    ]),
    relatedArticles: Object.freeze(["help/attendance/roll-call"]),
    captureIds: Object.freeze(["M15"]),
    captureStatus: "guide-only",
    sourceGuide: "both",
    popular: true,
    navigate: nav("/presences", "TeacherAttendance", "Présences:READ"),
  },
  {
    id: "help/attendance/roll-call",
    title: "Enregistrer un appel",
    summary: "L’enregistrement de l’appel n’est proposé que si votre rôle peut modifier les présences.",
    roles: SCHOOL_STAFF_ROLES,
    permissions: Object.freeze(["Présences:UPDATE"]),
    platforms: BOTH,
    routeKeys: Object.freeze([HELP_SCREEN.ATTENDANCE]),
    keywords: Object.freeze(["appel", "présent", "absent", "retard", "justifié", "enregistrer"]),
    steps: Object.freeze([
      "Pour chaque élève, choisissez Présent, Absent, Retard ou Justifié.",
      "Utilisez Tous présents / Tout présent uniquement après avoir vérifié le roster.",
      "Cliquez ou appuyez sur Enregistrer l’appel et attendez la confirmation.",
      "Si l’appel est conservé en file d’attente, il n’est pas encore confirmé serveur. Ne répétez pas immédiatement la saisie.",
    ]),
    relatedArticles: Object.freeze(["help/attendance/choose-class", "help/sync/queued"]),
    captureIds: Object.freeze(["M16"]),
    captureStatus: "guide-only",
    sourceGuide: "both",
    popular: false,
    navigate: nav("/presences", "TeacherAttendance", "Présences:UPDATE"),
  },
  {
    id: "help/grades/evaluations",
    title: "Notes et évaluations",
    summary: "Le module Notes permet de consulter les évaluations autorisées pour la session.",
    roles: SCHOOL_STAFF_ROLES.filter((role) => role !== HELP_ROLE.ACCOUNTANT),
    permissions: Object.freeze(["Notes:READ"]),
    platforms: BOTH,
    routeKeys: Object.freeze([HELP_SCREEN.GRADES, HELP_SCREEN.DASHBOARD]),
    keywords: Object.freeze(["notes", "évaluations", "barème"]),
    steps: Object.freeze([
      "Ouvrez Notes.",
      "Sur le Web, le module comporte les onglets Évaluations, Saisie des notes, Par classe, Par élève et Statistiques.",
      "Consultez uniquement les évaluations et listes autorisées pour votre session.",
      "Si une action de création ou de saisie n’apparaît pas, ne cherchez pas à la contourner : elle dépend des droits et de l’état de l’établissement.",
    ]),
    relatedArticles: Object.freeze(["help/rbac/missing-action"]),
    captureIds: Object.freeze(["M17"]),
    captureStatus: "guide-only",
    sourceGuide: "both",
    popular: false,
    navigate: nav("/notes", "TeacherGrades", "Notes:READ"),
  },
  {
    id: "help/payments/overview",
    title: "Consulter les paiements",
    summary: "Le module Paiements permet de consulter les encaissements scolaires du périmètre autorisé.",
    roles: Object.freeze([
      HELP_ROLE.SCHOOL_ADMIN,
      HELP_ROLE.PRINCIPAL,
      HELP_ROLE.PROVISEUR,
      HELP_ROLE.SECRETARY,
      HELP_ROLE.ACCOUNTANT,
    ]),
    permissions: Object.freeze(["Paiements:READ"]),
    platforms: BOTH,
    routeKeys: Object.freeze([HELP_SCREEN.PAYMENTS, HELP_SCREEN.DASHBOARD]),
    keywords: Object.freeze(["paiements", "frais", "reçus", "impayés", "finances"]),
    steps: Object.freeze([
      "Ouvrez Finances → Paiements (Web) ou Paiements (Mobile).",
      "Consultez la synthèse et les reçus récents lorsqu’ils sont chargés.",
      "Les modules Frais et Impayés sont accessibles depuis Finances selon les permissions.",
    ]),
    relatedArticles: Object.freeze(["help/payments/record"]),
    captureIds: Object.freeze(["M12", "M14"]),
    captureStatus: "guide-only",
    sourceGuide: "both",
    popular: true,
    navigate: nav("/finances", "Payments", "Paiements:READ"),
  },
  {
    id: "help/payments/record",
    title: "Saisir un paiement",
    summary:
      "La saisie n’est un encaissement confirmé qu’après acceptation serveur. Une file d’attente n’est pas un succès.",
    roles: Object.freeze([
      HELP_ROLE.SCHOOL_ADMIN,
      HELP_ROLE.PRINCIPAL,
      HELP_ROLE.SECRETARY,
      HELP_ROLE.ACCOUNTANT,
    ]),
    permissions: Object.freeze(["Paiements:CREATE"]),
    platforms: BOTH,
    routeKeys: Object.freeze([HELP_SCREEN.PAYMENTS]),
    keywords: Object.freeze(["saisir", "paiement", "montant", "espèces", "mobile money", "reçu"]),
    steps: Object.freeze([
      "Si Saisir un paiement / l’action de création est visible, ouvrez-la. Sur Mobile, le bouton peut être masqué tant qu’aucun reçu n’est chargé.",
      "Identifiez l’élève, vérifiez sa classe lorsque le formulaire le demande, puis le ou les frais concernés.",
      "Saisissez le montant et le moyen de paiement, puis validez.",
      "Ne considérez le paiement comme enregistré qu’après confirmation de Somafrik. Contrôlez le reçu après actualisation.",
      "Ne percevez pas une deuxième fois le même montant simplement parce que la connexion est lente.",
    ]),
    relatedArticles: Object.freeze(["help/payments/overview", "help/sync/queued"]),
    captureIds: Object.freeze(["M13", "M14"]),
    captureStatus: "guide-only",
    sourceGuide: "both",
    popular: false,
    navigate: nav("/finances", "Payments", "Paiements:CREATE"),
  },
  {
    id: "help/planning/overview",
    title: "Planning de cours",
    summary: "Le menu Planning donne accès, selon les droits, au calendrier et aux vues par classe, enseignant ou salle.",
    roles: SCHOOL_STAFF_ROLES,
    permissions: Object.freeze(["Planning de cours:READ"]),
    platforms: BOTH,
    routeKeys: Object.freeze([HELP_SCREEN.PLANNING]),
    keywords: Object.freeze(["planning", "emploi du temps", "salles", "remplacements"]),
    steps: Object.freeze([
      "Ouvrez Planning (Web) ou Emploi du temps (Mobile) lorsque l’entrée est visible.",
      "Utilisez uniquement les actions visibles dans votre périmètre.",
      "Les affectations pédagogiques d’un enseignant se gèrent depuis l’écran Enseignants lorsque l’action est disponible.",
    ]),
    relatedArticles: Object.freeze(["help/teachers/assign-course"]),
    captureIds: [],
    captureStatus: "guide-only",
    sourceGuide: "both",
    popular: false,
    navigate: nav("/planning", "Timetable", "Planning de cours:READ"),
  },
  {
    id: "help/communication/messages",
    title: "Messages",
    summary: "Les messages sont des échanges ciblés selon le périmètre autorisé. Ce n’est pas l’aide produit ni le Support.",
    roles: AUTHENTICATED_HELP_ROLES,
    permissions: Object.freeze(["Messages:READ"]),
    platforms: BOTH,
    routeKeys: Object.freeze([HELP_SCREEN.MESSAGES]),
    keywords: Object.freeze(["messages", "messagerie", "échanges"]),
    steps: Object.freeze([
      "Ouvrez Messages depuis la cloche / topbar (Web) ou le menu (Mobile) lorsque l’entrée est visible.",
      "La visibilité dépend du rôle et de Messages:READ.",
      "L’écran Support Mobile n’est pas un catalogue d’aide et n’est pas fusionné avec cette procédure.",
    ]),
    relatedArticles: Object.freeze(["help/communication/announcements"]),
    captureIds: [],
    captureStatus: "guide-only",
    sourceGuide: "both",
    popular: false,
    navigate: nav(null, "Messages", "Messages:READ"),
  },
  {
    id: "help/communication/announcements",
    title: "Annonces",
    summary: "Les annonces sont des informations publiées à un ensemble de destinataires.",
    roles: AUTHENTICATED_HELP_ROLES,
    permissions: Object.freeze(["Announcements:READ"]),
    platforms: BOTH,
    routeKeys: Object.freeze([HELP_SCREEN.ANNOUNCEMENTS]),
    keywords: Object.freeze(["annonces", "publication", "destinataires"]),
    steps: Object.freeze([
      "Ouvrez Annonces lorsque le module est disponible pour votre rôle.",
      "Consultez uniquement les publications de votre périmètre.",
    ]),
    relatedArticles: Object.freeze(["help/communication/messages"]),
    captureIds: [],
    captureStatus: "guide-only",
    sourceGuide: "both",
    popular: false,
    navigate: nav(null, "Announcements", "Announcements:READ"),
  },
  {
    id: "help/communication/notifications",
    title: "Notifications",
    summary: "Les notifications signalent des événements de plateforme ou d’établissement lorsque le module est disponible.",
    roles: AUTHENTICATED_HELP_ROLES,
    permissions: Object.freeze(["Notifications:READ"]),
    platforms: BOTH,
    routeKeys: Object.freeze([HELP_SCREEN.NOTIFICATIONS]),
    keywords: Object.freeze(["notifications", "cloche", "événements"]),
    steps: Object.freeze([
      "Ouvrez Notifications depuis la cloche Web ou le menu Mobile lorsque l’entrée est visible.",
      "La visibilité de la page dépend du rôle et de Notifications:READ.",
    ]),
    relatedArticles: [],
    captureIds: [],
    captureStatus: "guide-only",
    sourceGuide: "both",
    popular: false,
    navigate: nav("/notifications", "InternalNotifications", "Notifications:READ"),
  },
  {
    id: "help/parent/home",
    title: "Espace parent",
    summary:
      "Les onglets parent permettent de consulter le profil, les notes, les présences et les frais des enfants liés à l’identité.",
    roles: Object.freeze([HELP_ROLE.PARENT]),
    permissions: [],
    platforms: Object.freeze([MOBILE]),
    routeKeys: Object.freeze([HELP_SCREEN.PARENT_HOME, HELP_SCREEN.DASHBOARD]),
    keywords: Object.freeze(["parent", "accueil", "profil", "notes", "présence", "frais", "enfant"]),
    steps: Object.freeze([
      "Depuis l’accueil, utilisez les onglets Profil, Notes, Présence et Frais selon les droits disponibles.",
      "Le parent ne doit voir que les données des enfants liés à son identité.",
      "Si une donnée d’un autre élève apparaît, ne poursuivez pas la consultation et signalez l’anomalie à l’administration de l’établissement.",
      "Cette aide ne décrit aucun parcours d’écriture pour lier un parent à un enfant.",
    ]),
    relatedArticles: Object.freeze(["help/rbac/missing-action"]),
    captureIds: Object.freeze(["M20"]),
    captureStatus: "validated",
    sourceGuide: "mobile",
    popular: true,
    navigate: nav(null, "Home", null),
  },
  {
    id: "help/student/home",
    title: "Espace élève",
    summary: "Les onglets élève permettent de consulter le profil, les notes, les présences et les frais.",
    roles: Object.freeze([HELP_ROLE.STUDENT]),
    permissions: [],
    platforms: Object.freeze([MOBILE]),
    routeKeys: Object.freeze([HELP_SCREEN.STUDENT_HOME, HELP_SCREEN.DASHBOARD]),
    keywords: Object.freeze(["élève", "accueil", "profil", "notes", "présence", "frais"]),
    steps: Object.freeze([
      "Depuis l’accueil, utilisez les onglets Profil, Notes, Présence et Frais.",
      "Le menu complémentaire peut proposer Emploi du temps, Bulletins, Messages ou Annonces selon les permissions.",
    ]),
    relatedArticles: Object.freeze(["help/rbac/missing-action"]),
    captureIds: Object.freeze(["M21"]),
    captureStatus: "validated",
    sourceGuide: "mobile",
    popular: true,
    navigate: nav(null, "Home", null),
  },
  {
    id: "help/sync/queued",
    title: "File d’attente et synchronisation",
    summary: "Une mutation en file d’attente n’est pas un enregistrement serveur réussi.",
    roles: SCHOOL_STAFF_ROLES,
    permissions: [],
    platforms: Object.freeze([MOBILE]),
    routeKeys: Object.freeze([HELP_SCREEN.SYNC, HELP_SCREEN.PAYMENTS, HELP_SCREEN.ATTENDANCE, HELP_SCREEN.GRADES]),
    keywords: Object.freeze(["hors ligne", "file", "synchronisation", "attente", "confirmé", "échec"]),
    steps: Object.freeze([
      "Somafrik distingue confirmé (serveur accepté), en attente / file d’attente, et échec.",
      "Si Internet disparaît, ne répétez pas immédiatement une opération sensible (paiement, appel, note).",
      "Lisez le message affiché, puis ouvrez Synchronisation ou Mode hors ligne si votre rôle y a accès.",
      "Après le retour du réseau, relancez la synchronisation, rechargez l’écran métier et vérifiez que la donnée existe côté serveur.",
    ]),
    relatedArticles: Object.freeze(["help/payments/record", "help/attendance/roll-call"]),
    captureIds: Object.freeze(["M23"]),
    captureStatus: "validated",
    sourceGuide: "mobile",
    popular: false,
    navigate: nav(null, "Synchronization", null),
  },
  {
    id: "help/settings/overview",
    title: "Paramètres de l’établissement",
    summary:
      "Le hub Paramètres oriente la configuration de l’établissement. Une carte visible ou un badge Disponible ne signifie pas que tout est modifiable.",
    roles: SCHOOL_SETTINGS_ROLES,
    permissions: Object.freeze(["Paramètres Établissement:READ"]),
    platforms: BOTH,
    routeKeys: Object.freeze([HELP_SCREEN.SETTINGS]),
    keywords: Object.freeze(["paramètres", "configuration", "année scolaire", "structure", "profil", "parcours"]),
    steps: Object.freeze([
      "Ouvrez Paramètres (Web) ou Paramètres (Mobile) lorsque l’entrée est visible. Sur Web, cet espace est réservé à l’administrateur d’établissement.",
      "Parcours recommandé : 1. Profil établissement. 2. Année scolaire. 3. Périodes et barème. 4. Structure pédagogique. 5. Cours. 6. Classes (Mon établissement → Classes). 7. Utilisateurs. 8. Enseignants. 9. Affectations. 10. Finances. 11. Planning. 12. Notes.",
      "L’année scolaire se configure dans Paramètres → Année scolaire, sur Web et sur Mobile. Elle doit exister avant de créer les classes.",
      "Certaines cartes (Notifications, Apparence, Intégrations) affichent Bientôt : cette fonctionnalité n’est pas encore disponible.",
      "Rôles et droits, Sécurité et l’export de données se consultent ; ils ne sont pas tous des écrans de configuration.",
    ]),
    relatedArticles: Object.freeze([
      "help/settings/profile",
      "help/settings/academic-year",
      "help/settings/pedagogical-structure",
      "help/settings/coming-soon",
      "help/rbac/missing-action",
    ]),
    captureIds: Object.freeze(["M22"]),
    captureStatus: "guide-only",
    sourceGuide: "both",
    popular: true,
    navigate: nav("/parametres", "Configuration", "Paramètres Établissement:READ"),
  },
  {
    id: "help/settings/profile",
    title: "Configurer le profil de l’établissement",
    summary:
      "Le profil regroupe l’identité, les contacts et le responsable légal. Le code, le pays et la ville ne sont pas modifiables côté établissement.",
    roles: SCHOOL_SETTINGS_ROLES,
    permissions: Object.freeze(["Paramètres Établissement:READ"]),
    platforms: BOTH,
    routeKeys: Object.freeze([HELP_SCREEN.SETTINGS_PROFILE]),
    keywords: Object.freeze(["profil", "logo", "adresse", "téléphone", "e-mail", "responsable", "code", "pays", "ville"]),
    steps: Object.freeze([
      "Ouvrez Paramètres → Profil établissement (Web) ou Paramètres → Profil établissement (Mobile).",
      "Vous pouvez consulter le nom, le type, le code, le pays, la ville, l’adresse, le téléphone, l’e-mail, le logo, le responsable légal et ses contacts.",
      "Si le bouton Enregistrer est visible, vous pouvez modifier : nom, type, adresse, téléphone, e-mail, nom / téléphone / e-mail du responsable, et le logo sous forme d’URL publique. Il n’y a pas d’envoi de fichier logo.",
      "Le code établissement n’est pas modifiable par l’administrateur d’établissement.",
      "Le pays et la ville sont affichés en lecture seule sur cet écran. Ne cherchez pas à les changer depuis le profil.",
    ]),
    relatedArticles: Object.freeze(["help/settings/overview", "help/rbac/missing-action"]),
    captureIds: [],
    captureStatus: "guide-only",
    sourceGuide: "both",
    popular: true,
    navigate: nav("/parametres/profil", "EstablishmentProfile", "Paramètres Établissement:READ"),
  },
  {
    id: "help/settings/academic-year",
    title: "Configurer l’année scolaire",
    summary:
      "L’année scolaire est le cadre des classes, des périodes, des notes et du planning. Elle se crée dans Paramètres, sur Web et Mobile.",
    roles: SCHOOL_SETTINGS_ROLES,
    permissions: Object.freeze(["Années Académiques:READ"]),
    platforms: BOTH,
    routeKeys: Object.freeze([HELP_SCREEN.SETTINGS_ACADEMIC_YEAR]),
    keywords: Object.freeze(["année scolaire", "année académique", "dates", "année courante", "créer"]),
    steps: Object.freeze([
      "Ouvrez Paramètres → Année scolaire (Web) ou Paramètres → Année scolaire (Mobile).",
      "Une année scolaire doit être configurée avant de pouvoir créer les classes et utiliser normalement plusieurs fonctions pédagogiques.",
      "Sans année scolaire, la création de classes est bloquée. Périodes, évaluations, notes, bulletins, affectations enseignants et planning en dépendent.",
      "Si Créer l’année est visible, saisissez le nom, la date de début, la date de fin, puis indiquez si elle est l’année courante.",
      "Pour une année déjà listée, Définir comme courante apparaît lorsque votre rôle peut la mettre à jour. Il n’existe pas de procédure de suppression ou de clôture sur cet écran.",
    ]),
    relatedArticles: Object.freeze([
      "help/settings/academic-periods",
      "help/settings/grading-configuration",
      "help/classes/create",
      "help/settings/overview",
    ]),
    captureIds: [],
    captureStatus: "guide-only",
    sourceGuide: "both",
    popular: true,
    navigate: nav("/parametres/annee-scolaire", "SchoolYearSettings", "Années Académiques:READ"),
  },
  {
    id: "help/settings/academic-periods",
    title: "Configurer les périodes de l’année scolaire",
    summary:
      "Les périodes (trimestre, semestre ou personnalisées) structurent les évaluations, les notes et les bulletins. Aucune clôture n’est proposée ici.",
    roles: SCHOOL_SETTINGS_ROLES,
    permissions: Object.freeze(["Paramètres Établissement:READ"]),
    platforms: BOTH,
    routeKeys: Object.freeze([HELP_SCREEN.SETTINGS_ACADEMIC_YEAR]),
    keywords: Object.freeze(["périodes", "trimestre", "semestre", "dates", "période active"]),
    steps: Object.freeze([
      "Sur Paramètres → Année scolaire, ouvrez la section Périodes et barème.",
      "Choisissez le mode : trimestre, semestre, ou périodes personnalisées.",
      "Renseignez les dates des sous-périodes. La période en cours s’active selon la date du jour.",
      "Les évaluations, notes et bulletins s’appuient sur ces périodes. Configurez d’abord une année scolaire.",
      "Cet écran ne propose pas de clôturer ni de supprimer une année ou une période.",
    ]),
    relatedArticles: Object.freeze(["help/settings/academic-year", "help/settings/grading-configuration"]),
    captureIds: [],
    captureStatus: "guide-only",
    sourceGuide: "both",
    popular: true,
    navigate: nav("/parametres/annee-scolaire", "SchoolYearSettings", "Paramètres Établissement:READ"),
  },
  {
    id: "help/settings/grading-configuration",
    title: "Configurer le barème et les types d’évaluation",
    summary:
      "Le barème par défaut et les types d’évaluation servent de référentiel pédagogique. Cette aide ne décrit pas la saisie des notes enseignant.",
    roles: SCHOOL_SETTINGS_ROLES,
    permissions: Object.freeze(["Paramètres Établissement:READ"]),
    platforms: BOTH,
    routeKeys: Object.freeze([HELP_SCREEN.SETTINGS_ACADEMIC_YEAR]),
    keywords: Object.freeze(["barème", "types d’évaluation", "évaluation", "notes"]),
    steps: Object.freeze([
      "Sur Paramètres → Année scolaire, renseignez le barème par défaut utilisé par les évaluations.",
      "Configurez les types d’évaluation de l’établissement lorsque le panneau est visible.",
      "Ces réglages alimentent le module Notes : consultation des évaluations et listes autorisées.",
      "Cette aide ne publie pas de procédure pour créer une évaluation enseignant ni pour saisir des notes.",
    ]),
    relatedArticles: Object.freeze(["help/settings/academic-year", "help/grades/evaluations"]),
    captureIds: [],
    captureStatus: "guide-only",
    sourceGuide: "both",
    popular: true,
    navigate: nav("/parametres/annee-scolaire", "SchoolYearSettings", "Paramètres Établissement:READ"),
  },
  {
    id: "help/settings/pedagogical-structure",
    title: "Configurer la structure pédagogique",
    summary:
      "L’établissement active un sous-ensemble du référentiel national et gère ses cours. Les classes se créent dans Mon établissement, pas dans cette carte.",
    roles: SCHOOL_SETTINGS_ROLES,
    permissions: Object.freeze(["Paramètres Établissement:READ"]),
    platforms: BOTH,
    routeKeys: Object.freeze([HELP_SCREEN.SETTINGS_STRUCTURE]),
    keywords: Object.freeze(["structure", "niveaux", "filières", "cours", "matières", "référentiel", "classes"]),
    steps: Object.freeze([
      "Ouvrez Paramètres → Structure pédagogique (Web) ou Paramètres → Structure pédagogique (Mobile).",
      "Le référentiel national (niveaux, filières, séries, groupes) est créé au niveau plateforme / pays. L’établissement ne crée pas librement un niveau ou une filière nationale.",
      "Activez uniquement les éléments du référentiel qui concernent votre école, lorsque l’activation est visible.",
      "Vous pouvez gérer les cours de l’établissement (code, coefficient) selon vos permissions Matières.",
      "Les classes ne se créent pas dans cette carte. Parcours réel : Mon établissement → Classes, après configuration de l’année scolaire.",
    ]),
    relatedArticles: Object.freeze(["help/settings/academic-year", "help/classes/create", "help/teachers/assign-course"]),
    captureIds: [],
    captureStatus: "guide-only",
    sourceGuide: "both",
    popular: true,
    navigate: nav("/parametres/structure", "SchoolPedagogicalStructure", "Paramètres Établissement:READ"),
  },
  {
    id: "help/settings/roles-permissions",
    title: "Comprendre les rôles et les droits",
    summary:
      "Côté établissement, Rôles et droits est un catalogue en lecture seule. Seul le Super administrateur configure la matrice RBAC.",
    roles: SCHOOL_SETTINGS_ROLES,
    permissions: Object.freeze(["Paramètres Établissement:READ"]),
    platforms: BOTH,
    routeKeys: Object.freeze([HELP_SCREEN.SETTINGS_ROLES]),
    keywords: Object.freeze(["rôles", "droits", "permissions", "matrice", "catalogue", "lecture seule"]),
    steps: Object.freeze([
      "Ouvrez Paramètres → Rôles et droits (Web) ou Paramètres → Rôles disponibles (Mobile).",
      "Consultez les rôles affectables et les permissions affichées pour chaque rôle.",
      "Un administrateur d’établissement ne modifie pas la matrice globale CRUD et ne crée pas de rôle depuis cet écran.",
      "La création d’un utilisateur ne modifie jamais la matrice RBAC.",
      "Pour accorder un rôle existant à un compte : Mon établissement → Comptes utilisateurs → Attribuer.",
    ]),
    relatedArticles: Object.freeze(["help/users/assign-role", "help/users/create", "help/settings/overview"]),
    captureIds: [],
    captureStatus: "guide-only",
    sourceGuide: "both",
    popular: true,
    navigate: nav("/parametres/roles-droits", "SchoolAssignableRoles", "Paramètres Établissement:READ"),
  },
  {
    id: "help/settings/finance",
    title: "Configurer les paramètres financiers",
    summary:
      "Paramètres → Finances configure les grilles tarifaires. L’encaissement se fait dans Finances → Paiements. Les pénalités automatiques ne sont pas disponibles.",
    roles: SCHOOL_SETTINGS_ROLES,
    permissions: Object.freeze(["Frais & tarifs:READ"]),
    platforms: Object.freeze([WEB]),
    routeKeys: Object.freeze([HELP_SCREEN.SETTINGS_FINANCE]),
    keywords: Object.freeze(["finances", "grilles", "frais", "échéance", "devise", "moyens de paiement"]),
    steps: Object.freeze([
      "Ouvrez Paramètres → Finances. Cet écran est la configuration, distincte de Finances → Paiements (encaissement).",
      "La devise affichée est la devise canonique de l’établissement ou du pays. Vous ne saisissez pas une devise libre.",
      "Consultez ou, si Enregistrer le type de frais est visible, créez une grille : classe, année, type de frais, montant, échéance.",
      "Les moyens de paiement autorisés se consultent et s’activent ou se désactivent lorsque l’action est visible.",
      "Les pénalités de retard automatiques et un barème établissement de réductions ne sont pas disponibles. Mobile Money n’est pas une configuration d’établissement dans Paramètres.",
    ]),
    relatedArticles: Object.freeze(["help/payments/overview", "help/settings/overview"]),
    captureIds: [],
    captureStatus: "guide-only",
    sourceGuide: "web",
    popular: true,
    navigate: nav("/parametres/finances", null, "Frais & tarifs:READ"),
  },
  {
    id: "help/settings/data-export",
    title: "Exporter les données de l’établissement",
    summary:
      "L’export CSV et l’export JSON versionné sont disponibles. Il n’existe pas de sauvegarde ni de restauration complète.",
    roles: Object.freeze([HELP_ROLE.SCHOOL_ADMIN, HELP_ROLE.SUPER_ADMIN]),
    permissions: Object.freeze(["Paramètres Établissement:READ"]),
    platforms: Object.freeze([WEB]),
    routeKeys: Object.freeze([HELP_SCREEN.SETTINGS_DATA]),
    keywords: Object.freeze(["export", "csv", "json", "données", "sauvegarde", "restauration"]),
    steps: Object.freeze([
      "Ouvrez Paramètres → Données et sauvegarde.",
      "Export : OUI. Vous pouvez télécharger un extrait CSV des lignes affichées (élèves, classes, enseignants, etc.) et un export JSON versionné du périmètre autorisé.",
      "Les secrets (mot de passe, hash, jeton) sont exclus de l’export JSON.",
      "Sauvegarde/restauration complète : NON. Restore : NON. Rollback : NON.",
      "N’utilisez pas l’export JSON comme une sauvegarde complète de l’établissement.",
    ]),
    relatedArticles: Object.freeze(["help/settings/overview"]),
    captureIds: [],
    captureStatus: "guide-only",
    sourceGuide: "web",
    popular: true,
    navigate: nav("/parametres/donnees", null, "Paramètres Établissement:READ"),
  },
  {
    id: "help/settings/subscription",
    title: "Consulter mon abonnement",
    summary:
      "Mon abonnement affiche l’offre, le statut, les factures et les paiements en lecture. Le changement d’offre et la résiliation ne sont pas des opérations garanties.",
    roles: SCHOOL_SETTINGS_ROLES,
    permissions: [],
    platforms: Object.freeze([WEB]),
    routeKeys: Object.freeze([HELP_SCREEN.SETTINGS_SUBSCRIPTION]),
    keywords: Object.freeze(["abonnement", "offre", "factures", "paiements", "plan"]),
    steps: Object.freeze([
      "Ouvrez Paramètres → Mon abonnement.",
      "Consultez l’offre actuelle, le statut, les factures et les paiements lorsqu’ils sont chargés.",
      "Les écrans Changer d’offre et Résiliation peuvent être visibles. Ils ne constituent pas une opération réussie : l’enregistrement n’est pas persisté.",
      "Ne présentez pas un changement d’offre ou une résiliation comme effectués.",
    ]),
    relatedArticles: Object.freeze(["help/settings/overview"]),
    captureIds: [],
    captureStatus: "guide-only",
    sourceGuide: "web",
    popular: true,
    navigate: nav("/parametres/mon-abonnement", null, null),
  },
  {
    id: "help/settings/security",
    title: "Comprendre les paramètres de sécurité",
    summary:
      "La page Sécurité est en lecture seule : session, règles affichées et journal. L’établissement n’y configure pas la politique d’accès.",
    roles: Object.freeze([HELP_ROLE.SCHOOL_ADMIN, HELP_ROLE.SUPER_ADMIN]),
    permissions: Object.freeze(["Paramètres Établissement:READ"]),
    platforms: Object.freeze([WEB]),
    routeKeys: Object.freeze([HELP_SCREEN.SETTINGS_SECURITY]),
    keywords: Object.freeze(["sécurité", "session", "mot de passe", "pin", "audit", "lecture seule"]),
    steps: Object.freeze([
      "Ouvrez Paramètres → Sécurité.",
      "Consultez la session active (utilisateur, rôle, établissement, portée), les règles de mot de passe affichées, le code PIN Mobile (6 chiffres) et le journal d’audit filtrable.",
      "Cette page est en lecture seule. L’établissement n’y configure pas la longueur du mot de passe, la complexité, la durée de session, le MFA, le lockout ni l’historique des mots de passe.",
      "Vous pouvez exporter le journal affiché en CSV. Ce n’est pas une configuration de politique.",
    ]),
    relatedArticles: Object.freeze(["help/settings/overview"]),
    captureIds: [],
    captureStatus: "guide-only",
    sourceGuide: "web",
    popular: true,
    navigate: nav("/parametres/securite", null, "Paramètres Établissement:READ"),
  },
  {
    id: "help/settings/coming-soon",
    title: "Fonctions Paramètres bientôt disponibles",
    summary:
      "Certaines cartes Paramètres sont visibles avec le badge Bientôt. Cette fonctionnalité n’est pas encore disponible.",
    roles: SCHOOL_SETTINGS_ROLES,
    permissions: Object.freeze(["Paramètres Établissement:READ"]),
    platforms: Object.freeze([WEB]),
    routeKeys: Object.freeze([HELP_SCREEN.SETTINGS_COMING_SOON, HELP_SCREEN.SETTINGS]),
    keywords: Object.freeze(["bientôt", "notifications", "apparence", "intégrations", "coming soon"]),
    steps: Object.freeze([
      "Les cartes Notifications, Apparence et Intégrations peuvent apparaître dans le hub Paramètres.",
      "Cette fonctionnalité n’est pas encore disponible. Aucune procédure de configuration n’est fournie.",
      "Le logo se gère déjà dans Profil établissement (URL). La réception de messages ou notifications ailleurs n’équivaut pas à configurer ces cartes.",
    ]),
    relatedArticles: Object.freeze(["help/settings/overview", "help/settings/profile"]),
    captureIds: [],
    captureStatus: "guide-only",
    sourceGuide: "web",
    popular: false,
    navigate: nav("/parametres", null, "Paramètres Établissement:READ"),
  },
];

export const HELP_CATALOG = freezeCatalog(ARTICLES);
