-- P0 — réconciliation RBAC système (idempotente, additive, transactionnelle).
-- Source : backend/lib/canonicalSystemRoles.js
-- INTERDIT : exécuter sur Somafrik-prod depuis Cursor. GO CTO obligatoire.

BEGIN;

CREATE TEMP TABLE _p0_system_roles (
  role_code TEXT PRIMARY KEY,
  role_name TEXT NOT NULL,
  scope TEXT NOT NULL,
  display_order INTEGER NOT NULL,
  school_assignable BOOLEAN NOT NULL
) ON COMMIT DROP;

INSERT INTO _p0_system_roles (role_code, role_name, scope, display_order, school_assignable) VALUES
  ('SUPER_ADMIN', 'Super Administrateur Somafrik', 'platform', -30, FALSE),
  ('COUNTRY_ADMIN', 'Admin Pays', 'country', -20, FALSE),
  ('SCHOOL_ADMIN', 'Admin School', 'school', -10, FALSE),
  ('PROVISEUR', 'Proviseur', 'school', 0, TRUE),
  ('PREFET_ETUDES', 'Préfet des études', 'school', 1, TRUE),
  ('PRINCIPAL', 'Directeur', 'school', 2, TRUE),
  ('SECRETARY', 'Secrétaire', 'school', 3, TRUE),
  ('TEACHER', 'Enseignant', 'school', 4, TRUE),
  ('PARENT', 'Parent', 'school', 5, FALSE),
  ('STUDENT', 'Élève / Étudiant', 'school', 6, FALSE),
  ('ACCOUNTANT', 'Comptable', 'school', 7, TRUE),
  ('SUPERVISOR', 'Surveillant', 'school', 8, TRUE);

CREATE TEMP TABLE _p0_system_permissions (
  role_name TEXT NOT NULL,
  permission TEXT NOT NULL,
  PRIMARY KEY (role_name, permission)
) ON COMMIT DROP;

INSERT INTO _p0_system_permissions (role_name, permission) VALUES
  ('Super Administrateur Somafrik', 'Abonnements:CREATE'),
  ('Super Administrateur Somafrik', 'Abonnements:DELETE'),
  ('Super Administrateur Somafrik', 'Abonnements:READ'),
  ('Super Administrateur Somafrik', 'Abonnements:SUSPEND'),
  ('Super Administrateur Somafrik', 'Abonnements:UPDATE'),
  ('Super Administrateur Somafrik', 'Affectations:CREATE'),
  ('Super Administrateur Somafrik', 'Affectations:DELETE'),
  ('Super Administrateur Somafrik', 'Affectations:READ'),
  ('Super Administrateur Somafrik', 'Affectations:SUSPEND'),
  ('Super Administrateur Somafrik', 'Affectations:UPDATE'),
  ('Super Administrateur Somafrik', 'Affecter un administrateur pays'),
  ('Super Administrateur Somafrik', 'Ajouter enseignants'),
  ('Super Administrateur Somafrik', 'Années Académiques:CREATE'),
  ('Super Administrateur Somafrik', 'Années Académiques:DELETE'),
  ('Super Administrateur Somafrik', 'Années Académiques:READ'),
  ('Super Administrateur Somafrik', 'Années Académiques:SUSPEND'),
  ('Super Administrateur Somafrik', 'Années Académiques:UPDATE'),
  ('Super Administrateur Somafrik', 'Announcements:CREATE'),
  ('Super Administrateur Somafrik', 'Announcements:DELETE'),
  ('Super Administrateur Somafrik', 'Announcements:READ'),
  ('Super Administrateur Somafrik', 'Announcements:SUSPEND'),
  ('Super Administrateur Somafrik', 'Announcements:UPDATE'),
  ('Super Administrateur Somafrik', 'Auditer connexions'),
  ('Super Administrateur Somafrik', 'Auditer utilisateurs pays'),
  ('Super Administrateur Somafrik', 'Bulletins:CREATE'),
  ('Super Administrateur Somafrik', 'Bulletins:DELETE'),
  ('Super Administrateur Somafrik', 'Bulletins:READ'),
  ('Super Administrateur Somafrik', 'Bulletins:SUSPEND'),
  ('Super Administrateur Somafrik', 'Bulletins:UPDATE'),
  ('Super Administrateur Somafrik', 'Classes:CREATE'),
  ('Super Administrateur Somafrik', 'Classes:DELETE'),
  ('Super Administrateur Somafrik', 'Classes:READ'),
  ('Super Administrateur Somafrik', 'Classes:SUSPEND'),
  ('Super Administrateur Somafrik', 'Classes:UPDATE'),
  ('Super Administrateur Somafrik', 'Contacts:CREATE'),
  ('Super Administrateur Somafrik', 'Contacts:DELETE'),
  ('Super Administrateur Somafrik', 'Contacts:READ'),
  ('Super Administrateur Somafrik', 'Contacts:SUSPEND'),
  ('Super Administrateur Somafrik', 'Contacts:UPDATE'),
  ('Super Administrateur Somafrik', 'Contrôler tous les établissements'),
  ('Super Administrateur Somafrik', 'Contrôler tous les pays'),
  ('Super Administrateur Somafrik', 'Créer notes'),
  ('Super Administrateur Somafrik', 'Créer rapports disciplinaires'),
  ('Super Administrateur Somafrik', 'Créer un établissement'),
  ('Super Administrateur Somafrik', 'Créer un pays'),
  ('Super Administrateur Somafrik', 'Demander pièces complémentaires'),
  ('Super Administrateur Somafrik', 'Documents:CREATE'),
  ('Super Administrateur Somafrik', 'Documents:DELETE'),
  ('Super Administrateur Somafrik', 'Documents:READ'),
  ('Super Administrateur Somafrik', 'Documents:SUSPEND'),
  ('Super Administrateur Somafrik', 'Documents:UPDATE'),
  ('Super Administrateur Somafrik', 'Élèves:CREATE'),
  ('Super Administrateur Somafrik', 'Élèves:DELETE'),
  ('Super Administrateur Somafrik', 'Élèves:READ'),
  ('Super Administrateur Somafrik', 'Élèves:SUSPEND'),
  ('Super Administrateur Somafrik', 'Élèves:UPDATE'),
  ('Super Administrateur Somafrik', 'Enseignants:CREATE'),
  ('Super Administrateur Somafrik', 'Enseignants:DELETE'),
  ('Super Administrateur Somafrik', 'Enseignants:READ'),
  ('Super Administrateur Somafrik', 'Enseignants:SUSPEND'),
  ('Super Administrateur Somafrik', 'Enseignants:UPDATE'),
  ('Super Administrateur Somafrik', 'Établissements:CREATE'),
  ('Super Administrateur Somafrik', 'Établissements:DELETE'),
  ('Super Administrateur Somafrik', 'Établissements:READ'),
  ('Super Administrateur Somafrik', 'Établissements:SUSPEND'),
  ('Super Administrateur Somafrik', 'Établissements:UPDATE'),
  ('Super Administrateur Somafrik', 'Examens:CREATE'),
  ('Super Administrateur Somafrik', 'Examens:DELETE'),
  ('Super Administrateur Somafrik', 'Examens:READ'),
  ('Super Administrateur Somafrik', 'Examens:SUSPEND'),
  ('Super Administrateur Somafrik', 'Examens:UPDATE'),
  ('Super Administrateur Somafrik', 'Faire appel'),
  ('Super Administrateur Somafrik', 'Frais & tarifs:CREATE'),
  ('Super Administrateur Somafrik', 'Frais & tarifs:DELETE'),
  ('Super Administrateur Somafrik', 'Frais & tarifs:READ'),
  ('Super Administrateur Somafrik', 'Frais & tarifs:SUSPEND'),
  ('Super Administrateur Somafrik', 'Frais & tarifs:UPDATE'),
  ('Super Administrateur Somafrik', 'Gérer abonnements'),
  ('Super Administrateur Somafrik', 'Gérer administrateurs écoles'),
  ('Super Administrateur Somafrik', 'Gérer administrateurs pays'),
  ('Super Administrateur Somafrik', 'Gérer admins écoles du pays'),
  ('Super Administrateur Somafrik', 'Gérer annonces'),
  ('Super Administrateur Somafrik', 'Gérer appels'),
  ('Super Administrateur Somafrik', 'Gérer classes'),
  ('Super Administrateur Somafrik', 'Gérer cours'),
  ('Super Administrateur Somafrik', 'Gérer discipline'),
  ('Super Administrateur Somafrik', 'Gérer élèves'),
  ('Super Administrateur Somafrik', 'Gérer établissements du pays'),
  ('Super Administrateur Somafrik', 'Gérer paiements'),
  ('Super Administrateur Somafrik', 'Gérer planning académique'),
  ('Super Administrateur Somafrik', 'Gérer utilisateurs'),
  ('Super Administrateur Somafrik', 'Matières:CREATE'),
  ('Super Administrateur Somafrik', 'Matières:DELETE'),
  ('Super Administrateur Somafrik', 'Matières:READ'),
  ('Super Administrateur Somafrik', 'Matières:SUSPEND'),
  ('Super Administrateur Somafrik', 'Matières:UPDATE'),
  ('Super Administrateur Somafrik', 'Messages école'),
  ('Super Administrateur Somafrik', 'Messages parents'),
  ('Super Administrateur Somafrik', 'Messages:CREATE'),
  ('Super Administrateur Somafrik', 'Messages:DELETE'),
  ('Super Administrateur Somafrik', 'Messages:READ'),
  ('Super Administrateur Somafrik', 'Messages:SUSPEND'),
  ('Super Administrateur Somafrik', 'Messages:UPDATE'),
  ('Super Administrateur Somafrik', 'Modifier notes'),
  ('Super Administrateur Somafrik', 'Modifier présences'),
  ('Super Administrateur Somafrik', 'Modifier tarifs par pays'),
  ('Super Administrateur Somafrik', 'Modifier un établissement'),
  ('Super Administrateur Somafrik', 'Modifier un pays'),
  ('Super Administrateur Somafrik', 'Notes:CREATE'),
  ('Super Administrateur Somafrik', 'Notes:DELETE'),
  ('Super Administrateur Somafrik', 'Notes:READ'),
  ('Super Administrateur Somafrik', 'Notes:SUSPEND'),
  ('Super Administrateur Somafrik', 'Notes:UPDATE'),
  ('Super Administrateur Somafrik', 'Notifications:CREATE'),
  ('Super Administrateur Somafrik', 'Notifications:DELETE'),
  ('Super Administrateur Somafrik', 'Notifications:READ'),
  ('Super Administrateur Somafrik', 'Notifications:SUSPEND'),
  ('Super Administrateur Somafrik', 'Notifications:UPDATE'),
  ('Super Administrateur Somafrik', 'Organiser examens'),
  ('Super Administrateur Somafrik', 'Paiements:CREATE'),
  ('Super Administrateur Somafrik', 'Paiements:DELETE'),
  ('Super Administrateur Somafrik', 'Paiements:READ'),
  ('Super Administrateur Somafrik', 'Paiements:SUSPEND'),
  ('Super Administrateur Somafrik', 'Paiements:UPDATE'),
  ('Super Administrateur Somafrik', 'Paramètres Établissement:CREATE'),
  ('Super Administrateur Somafrik', 'Paramètres Établissement:DELETE'),
  ('Super Administrateur Somafrik', 'Paramètres Établissement:READ'),
  ('Super Administrateur Somafrik', 'Paramètres Établissement:SUSPEND'),
  ('Super Administrateur Somafrik', 'Paramètres Établissement:UPDATE'),
  ('Super Administrateur Somafrik', 'Pays:CREATE'),
  ('Super Administrateur Somafrik', 'Pays:DELETE'),
  ('Super Administrateur Somafrik', 'Pays:READ'),
  ('Super Administrateur Somafrik', 'Pays:SUSPEND'),
  ('Super Administrateur Somafrik', 'Pays:UPDATE'),
  ('Super Administrateur Somafrik', 'Planning de cours:CREATE'),
  ('Super Administrateur Somafrik', 'Planning de cours:DELETE'),
  ('Super Administrateur Somafrik', 'Planning de cours:READ'),
  ('Super Administrateur Somafrik', 'Planning de cours:SUSPEND'),
  ('Super Administrateur Somafrik', 'Planning de cours:UPDATE'),
  ('Super Administrateur Somafrik', 'Présences:CREATE'),
  ('Super Administrateur Somafrik', 'Présences:DELETE'),
  ('Super Administrateur Somafrik', 'Présences:READ'),
  ('Super Administrateur Somafrik', 'Présences:SUSPEND'),
  ('Super Administrateur Somafrik', 'Présences:UPDATE'),
  ('Super Administrateur Somafrik', 'Publier communications'),
  ('Super Administrateur Somafrik', 'Rapports:CREATE'),
  ('Super Administrateur Somafrik', 'Rapports:DELETE'),
  ('Super Administrateur Somafrik', 'Rapports:READ'),
  ('Super Administrateur Somafrik', 'Rapports:SUSPEND'),
  ('Super Administrateur Somafrik', 'Rapports:UPDATE'),
  ('Super Administrateur Somafrik', 'Réactiver un établissement'),
  ('Super Administrateur Somafrik', 'Réactiver un pays'),
  ('Super Administrateur Somafrik', 'Refuser une inscription'),
  ('Super Administrateur Somafrik', 'Relancer établissements en retard'),
  ('Super Administrateur Somafrik', 'Relations:CREATE'),
  ('Super Administrateur Somafrik', 'Relations:DELETE'),
  ('Super Administrateur Somafrik', 'Relations:READ'),
  ('Super Administrateur Somafrik', 'Relations:SUSPEND'),
  ('Super Administrateur Somafrik', 'Relations:UPDATE'),
  ('Super Administrateur Somafrik', 'Remplacements:CREATE'),
  ('Super Administrateur Somafrik', 'Remplacements:DELETE'),
  ('Super Administrateur Somafrik', 'Remplacements:READ'),
  ('Super Administrateur Somafrik', 'Remplacements:SUSPEND'),
  ('Super Administrateur Somafrik', 'Remplacements:UPDATE'),
  ('Super Administrateur Somafrik', 'Salles:CREATE'),
  ('Super Administrateur Somafrik', 'Salles:DELETE'),
  ('Super Administrateur Somafrik', 'Salles:READ'),
  ('Super Administrateur Somafrik', 'Salles:SUSPEND'),
  ('Super Administrateur Somafrik', 'Salles:UPDATE'),
  ('Super Administrateur Somafrik', 'Suivre abonnements pays'),
  ('Super Administrateur Somafrik', 'Supprimer un pays'),
  ('Super Administrateur Somafrik', 'Suspendre un établissement'),
  ('Super Administrateur Somafrik', 'Suspendre un pays'),
  ('Super Administrateur Somafrik', 'Utilisateurs:CREATE'),
  ('Super Administrateur Somafrik', 'Utilisateurs:DELETE'),
  ('Super Administrateur Somafrik', 'Utilisateurs:READ'),
  ('Super Administrateur Somafrik', 'Utilisateurs:SUSPEND'),
  ('Super Administrateur Somafrik', 'Utilisateurs:UPDATE'),
  ('Super Administrateur Somafrik', 'Valider années académiques'),
  ('Super Administrateur Somafrik', 'Valider bulletins'),
  ('Super Administrateur Somafrik', 'Valider examens'),
  ('Super Administrateur Somafrik', 'Valider une inscription'),
  ('Super Administrateur Somafrik', 'Voir bulletins'),
  ('Super Administrateur Somafrik', 'Voir classes'),
  ('Super Administrateur Somafrik', 'Voir documents'),
  ('Super Administrateur Somafrik', 'Voir élèves'),
  ('Super Administrateur Somafrik', 'Voir enfant'),
  ('Super Administrateur Somafrik', 'Voir enseignants'),
  ('Super Administrateur Somafrik', 'Voir examens'),
  ('Super Administrateur Somafrik', 'Voir notes'),
  ('Super Administrateur Somafrik', 'Voir paiements'),
  ('Super Administrateur Somafrik', 'Voir présences'),
  ('Super Administrateur Somafrik', 'Voir rapports'),
  ('Super Administrateur Somafrik', 'Voir rapports financiers'),
  ('Super Administrateur Somafrik', 'Voir rapports globaux'),
  ('Super Administrateur Somafrik', 'Voir rapports pays'),
  ('Admin Pays', 'Abonnements:CREATE'),
  ('Admin Pays', 'Abonnements:DELETE'),
  ('Admin Pays', 'Abonnements:READ'),
  ('Admin Pays', 'Abonnements:SUSPEND'),
  ('Admin Pays', 'Abonnements:UPDATE'),
  ('Admin Pays', 'Announcements:CREATE'),
  ('Admin Pays', 'Announcements:DELETE'),
  ('Admin Pays', 'Announcements:READ'),
  ('Admin Pays', 'Announcements:SUSPEND'),
  ('Admin Pays', 'Announcements:UPDATE'),
  ('Admin Pays', 'Auditer utilisateurs pays'),
  ('Admin Pays', 'Contacts:READ'),
  ('Admin Pays', 'Créer un établissement'),
  ('Admin Pays', 'Demander pièces complémentaires'),
  ('Admin Pays', 'Établissements:CREATE'),
  ('Admin Pays', 'Établissements:DELETE'),
  ('Admin Pays', 'Établissements:READ'),
  ('Admin Pays', 'Établissements:SUSPEND'),
  ('Admin Pays', 'Établissements:UPDATE'),
  ('Admin Pays', 'Gérer administrateurs écoles'),
  ('Admin Pays', 'Gérer admins écoles du pays'),
  ('Admin Pays', 'Gérer établissements du pays'),
  ('Admin Pays', 'Messages:CREATE'),
  ('Admin Pays', 'Messages:DELETE'),
  ('Admin Pays', 'Messages:READ'),
  ('Admin Pays', 'Messages:SUSPEND'),
  ('Admin Pays', 'Messages:UPDATE'),
  ('Admin Pays', 'Modifier un établissement'),
  ('Admin Pays', 'Notifications:CREATE'),
  ('Admin Pays', 'Notifications:DELETE'),
  ('Admin Pays', 'Notifications:READ'),
  ('Admin Pays', 'Notifications:SUSPEND'),
  ('Admin Pays', 'Notifications:UPDATE'),
  ('Admin Pays', 'Pays:READ'),
  ('Admin Pays', 'Rapports:READ'),
  ('Admin Pays', 'Réactiver un établissement'),
  ('Admin Pays', 'Refuser une inscription'),
  ('Admin Pays', 'Relancer établissements en retard'),
  ('Admin Pays', 'Suivre abonnements pays'),
  ('Admin Pays', 'Suspendre un établissement'),
  ('Admin Pays', 'Utilisateurs:CREATE'),
  ('Admin Pays', 'Utilisateurs:DELETE'),
  ('Admin Pays', 'Utilisateurs:READ'),
  ('Admin Pays', 'Utilisateurs:SUSPEND'),
  ('Admin Pays', 'Utilisateurs:UPDATE'),
  ('Admin Pays', 'Valider une inscription'),
  ('Admin Pays', 'Voir rapports pays'),
  ('Admin School', 'Affectations:CREATE'),
  ('Admin School', 'Affectations:READ'),
  ('Admin School', 'Affectations:UPDATE'),
  ('Admin School', 'Ajouter enseignants'),
  ('Admin School', 'Années Académiques:CREATE'),
  ('Admin School', 'Années Académiques:DELETE'),
  ('Admin School', 'Années Académiques:READ'),
  ('Admin School', 'Années Académiques:SUSPEND'),
  ('Admin School', 'Années Académiques:UPDATE'),
  ('Admin School', 'Announcements:CREATE'),
  ('Admin School', 'Announcements:DELETE'),
  ('Admin School', 'Announcements:READ'),
  ('Admin School', 'Announcements:SUSPEND'),
  ('Admin School', 'Announcements:UPDATE'),
  ('Admin School', 'Bulletins:READ'),
  ('Admin School', 'Classes:CREATE'),
  ('Admin School', 'Classes:DELETE'),
  ('Admin School', 'Classes:READ'),
  ('Admin School', 'Classes:SUSPEND'),
  ('Admin School', 'Classes:UPDATE'),
  ('Admin School', 'Contacts:CREATE'),
  ('Admin School', 'Contacts:DELETE'),
  ('Admin School', 'Contacts:READ'),
  ('Admin School', 'Contacts:SUSPEND'),
  ('Admin School', 'Contacts:UPDATE'),
  ('Admin School', 'Créer rapports disciplinaires'),
  ('Admin School', 'Documents:CREATE'),
  ('Admin School', 'Documents:DELETE'),
  ('Admin School', 'Documents:READ'),
  ('Admin School', 'Documents:SUSPEND'),
  ('Admin School', 'Documents:UPDATE'),
  ('Admin School', 'Élèves:CREATE'),
  ('Admin School', 'Élèves:DELETE'),
  ('Admin School', 'Élèves:READ'),
  ('Admin School', 'Élèves:SUSPEND'),
  ('Admin School', 'Élèves:UPDATE'),
  ('Admin School', 'Enseignants:CREATE'),
  ('Admin School', 'Enseignants:READ'),
  ('Admin School', 'Enseignants:UPDATE'),
  ('Admin School', 'Examens:CREATE'),
  ('Admin School', 'Examens:DELETE'),
  ('Admin School', 'Examens:READ'),
  ('Admin School', 'Examens:SUSPEND'),
  ('Admin School', 'Examens:UPDATE'),
  ('Admin School', 'Faire appel'),
  ('Admin School', 'Frais & tarifs:CREATE'),
  ('Admin School', 'Frais & tarifs:DELETE'),
  ('Admin School', 'Frais & tarifs:READ'),
  ('Admin School', 'Frais & tarifs:SUSPEND'),
  ('Admin School', 'Frais & tarifs:UPDATE'),
  ('Admin School', 'Gérer annonces'),
  ('Admin School', 'Gérer classes'),
  ('Admin School', 'Gérer cours'),
  ('Admin School', 'Gérer élèves'),
  ('Admin School', 'Gérer paiements'),
  ('Admin School', 'Gérer planning académique'),
  ('Admin School', 'Gérer utilisateurs'),
  ('Admin School', 'Matières:CREATE'),
  ('Admin School', 'Matières:DELETE'),
  ('Admin School', 'Matières:READ'),
  ('Admin School', 'Matières:SUSPEND'),
  ('Admin School', 'Matières:UPDATE'),
  ('Admin School', 'Messages parents'),
  ('Admin School', 'Messages:CREATE'),
  ('Admin School', 'Messages:DELETE'),
  ('Admin School', 'Messages:READ'),
  ('Admin School', 'Messages:SUSPEND'),
  ('Admin School', 'Messages:UPDATE'),
  ('Admin School', 'Modifier notes'),
  ('Admin School', 'Modifier présences'),
  ('Admin School', 'Notes:READ'),
  ('Admin School', 'Notifications:CREATE'),
  ('Admin School', 'Notifications:DELETE'),
  ('Admin School', 'Notifications:READ'),
  ('Admin School', 'Notifications:SUSPEND'),
  ('Admin School', 'Notifications:UPDATE'),
  ('Admin School', 'Paiements:READ'),
  ('Admin School', 'Paramètres Établissement:CREATE'),
  ('Admin School', 'Paramètres Établissement:DELETE'),
  ('Admin School', 'Paramètres Établissement:READ'),
  ('Admin School', 'Paramètres Établissement:SUSPEND'),
  ('Admin School', 'Paramètres Établissement:UPDATE'),
  ('Admin School', 'Planning de cours:CREATE'),
  ('Admin School', 'Planning de cours:DELETE'),
  ('Admin School', 'Planning de cours:READ'),
  ('Admin School', 'Planning de cours:SUSPEND'),
  ('Admin School', 'Planning de cours:UPDATE'),
  ('Admin School', 'Présences:READ'),
  ('Admin School', 'Publier communications'),
  ('Admin School', 'Rapports:CREATE'),
  ('Admin School', 'Rapports:DELETE'),
  ('Admin School', 'Rapports:READ'),
  ('Admin School', 'Rapports:SUSPEND'),
  ('Admin School', 'Rapports:UPDATE'),
  ('Admin School', 'Relations:CREATE'),
  ('Admin School', 'Relations:DELETE'),
  ('Admin School', 'Relations:READ'),
  ('Admin School', 'Relations:SUSPEND'),
  ('Admin School', 'Relations:UPDATE'),
  ('Admin School', 'Remplacements:CREATE'),
  ('Admin School', 'Remplacements:DELETE'),
  ('Admin School', 'Remplacements:READ'),
  ('Admin School', 'Remplacements:SUSPEND'),
  ('Admin School', 'Remplacements:UPDATE'),
  ('Admin School', 'Salles:CREATE'),
  ('Admin School', 'Salles:DELETE'),
  ('Admin School', 'Salles:READ'),
  ('Admin School', 'Salles:SUSPEND'),
  ('Admin School', 'Salles:UPDATE'),
  ('Admin School', 'Utilisateurs:CREATE'),
  ('Admin School', 'Utilisateurs:DELETE'),
  ('Admin School', 'Utilisateurs:READ'),
  ('Admin School', 'Utilisateurs:SUSPEND'),
  ('Admin School', 'Utilisateurs:UPDATE'),
  ('Admin School', 'Valider années académiques'),
  ('Admin School', 'Valider bulletins'),
  ('Admin School', 'Valider examens'),
  ('Admin School', 'Voir classes'),
  ('Admin School', 'Voir élèves'),
  ('Admin School', 'Voir enseignants'),
  ('Admin School', 'Voir notes'),
  ('Admin School', 'Voir présences'),
  ('Admin School', 'Voir rapports'),
  ('Admin School', 'Voir rapports financiers'),
  ('Proviseur', 'Affectations:CREATE'),
  ('Proviseur', 'Affectations:DELETE'),
  ('Proviseur', 'Affectations:READ'),
  ('Proviseur', 'Affectations:SUSPEND'),
  ('Proviseur', 'Affectations:UPDATE'),
  ('Proviseur', 'Années Académiques:READ'),
  ('Proviseur', 'Announcements:CREATE'),
  ('Proviseur', 'Announcements:DELETE'),
  ('Proviseur', 'Announcements:READ'),
  ('Proviseur', 'Announcements:SUSPEND'),
  ('Proviseur', 'Announcements:UPDATE'),
  ('Proviseur', 'Bulletins:CREATE'),
  ('Proviseur', 'Bulletins:DELETE'),
  ('Proviseur', 'Bulletins:READ'),
  ('Proviseur', 'Bulletins:SUSPEND'),
  ('Proviseur', 'Bulletins:UPDATE'),
  ('Proviseur', 'Classes:CREATE'),
  ('Proviseur', 'Classes:DELETE'),
  ('Proviseur', 'Classes:READ'),
  ('Proviseur', 'Classes:SUSPEND'),
  ('Proviseur', 'Classes:UPDATE'),
  ('Proviseur', 'Contacts:READ'),
  ('Proviseur', 'Documents:CREATE'),
  ('Proviseur', 'Documents:DELETE'),
  ('Proviseur', 'Documents:READ'),
  ('Proviseur', 'Documents:SUSPEND'),
  ('Proviseur', 'Documents:UPDATE'),
  ('Proviseur', 'Élèves:CREATE'),
  ('Proviseur', 'Élèves:DELETE'),
  ('Proviseur', 'Élèves:READ'),
  ('Proviseur', 'Élèves:SUSPEND'),
  ('Proviseur', 'Élèves:UPDATE'),
  ('Proviseur', 'Enseignants:READ'),
  ('Proviseur', 'Examens:CREATE'),
  ('Proviseur', 'Examens:DELETE'),
  ('Proviseur', 'Examens:READ'),
  ('Proviseur', 'Examens:SUSPEND'),
  ('Proviseur', 'Examens:UPDATE'),
  ('Proviseur', 'Frais & tarifs:READ'),
  ('Proviseur', 'Matières:CREATE'),
  ('Proviseur', 'Matières:DELETE'),
  ('Proviseur', 'Matières:READ'),
  ('Proviseur', 'Matières:SUSPEND'),
  ('Proviseur', 'Matières:UPDATE'),
  ('Proviseur', 'Messages:CREATE'),
  ('Proviseur', 'Messages:DELETE'),
  ('Proviseur', 'Messages:READ'),
  ('Proviseur', 'Messages:SUSPEND'),
  ('Proviseur', 'Messages:UPDATE'),
  ('Proviseur', 'Notes:CREATE'),
  ('Proviseur', 'Notes:DELETE'),
  ('Proviseur', 'Notes:READ'),
  ('Proviseur', 'Notes:SUSPEND'),
  ('Proviseur', 'Notes:UPDATE'),
  ('Proviseur', 'Notifications:CREATE'),
  ('Proviseur', 'Notifications:DELETE'),
  ('Proviseur', 'Notifications:READ'),
  ('Proviseur', 'Notifications:SUSPEND'),
  ('Proviseur', 'Notifications:UPDATE'),
  ('Proviseur', 'Paiements:READ'),
  ('Proviseur', 'Paramètres Établissement:READ'),
  ('Proviseur', 'Planning de cours:CREATE'),
  ('Proviseur', 'Planning de cours:DELETE'),
  ('Proviseur', 'Planning de cours:READ'),
  ('Proviseur', 'Planning de cours:SUSPEND'),
  ('Proviseur', 'Planning de cours:UPDATE'),
  ('Proviseur', 'Présences:CREATE'),
  ('Proviseur', 'Présences:DELETE'),
  ('Proviseur', 'Présences:READ'),
  ('Proviseur', 'Présences:SUSPEND'),
  ('Proviseur', 'Présences:UPDATE'),
  ('Proviseur', 'Publier communications'),
  ('Proviseur', 'Rapports:CREATE'),
  ('Proviseur', 'Rapports:DELETE'),
  ('Proviseur', 'Rapports:READ'),
  ('Proviseur', 'Rapports:SUSPEND'),
  ('Proviseur', 'Rapports:UPDATE'),
  ('Proviseur', 'Relations:READ'),
  ('Proviseur', 'Remplacements:CREATE'),
  ('Proviseur', 'Remplacements:DELETE'),
  ('Proviseur', 'Remplacements:READ'),
  ('Proviseur', 'Remplacements:SUSPEND'),
  ('Proviseur', 'Remplacements:UPDATE'),
  ('Proviseur', 'Salles:CREATE'),
  ('Proviseur', 'Salles:DELETE'),
  ('Proviseur', 'Salles:READ'),
  ('Proviseur', 'Salles:SUSPEND'),
  ('Proviseur', 'Salles:UPDATE'),
  ('Proviseur', 'Utilisateurs:READ'),
  ('Proviseur', 'Valider années académiques'),
  ('Proviseur', 'Valider bulletins'),
  ('Proviseur', 'Valider examens'),
  ('Proviseur', 'Voir classes'),
  ('Proviseur', 'Voir élèves'),
  ('Proviseur', 'Voir enseignants'),
  ('Proviseur', 'Voir rapports'),
  ('Proviseur', 'Voir rapports financiers'),
  ('Préfet des études', 'Affectations:CREATE'),
  ('Préfet des études', 'Affectations:DELETE'),
  ('Préfet des études', 'Affectations:READ'),
  ('Préfet des études', 'Affectations:SUSPEND'),
  ('Préfet des études', 'Affectations:UPDATE'),
  ('Préfet des études', 'Années Académiques:READ'),
  ('Préfet des études', 'Announcements:CREATE'),
  ('Préfet des études', 'Announcements:DELETE'),
  ('Préfet des études', 'Announcements:READ'),
  ('Préfet des études', 'Announcements:SUSPEND'),
  ('Préfet des études', 'Announcements:UPDATE'),
  ('Préfet des études', 'Bulletins:CREATE'),
  ('Préfet des études', 'Bulletins:DELETE'),
  ('Préfet des études', 'Bulletins:READ'),
  ('Préfet des études', 'Bulletins:SUSPEND'),
  ('Préfet des études', 'Bulletins:UPDATE'),
  ('Préfet des études', 'Classes:CREATE'),
  ('Préfet des études', 'Classes:DELETE'),
  ('Préfet des études', 'Classes:READ'),
  ('Préfet des études', 'Classes:SUSPEND'),
  ('Préfet des études', 'Classes:UPDATE'),
  ('Préfet des études', 'Contacts:READ'),
  ('Préfet des études', 'Créer notes'),
  ('Préfet des études', 'Créer rapports disciplinaires'),
  ('Préfet des études', 'Documents:CREATE'),
  ('Préfet des études', 'Documents:DELETE'),
  ('Préfet des études', 'Documents:READ'),
  ('Préfet des études', 'Documents:SUSPEND'),
  ('Préfet des études', 'Documents:UPDATE'),
  ('Préfet des études', 'Élèves:CREATE'),
  ('Préfet des études', 'Élèves:DELETE'),
  ('Préfet des études', 'Élèves:READ'),
  ('Préfet des études', 'Élèves:SUSPEND'),
  ('Préfet des études', 'Élèves:UPDATE'),
  ('Préfet des études', 'Enseignants:DELETE'),
  ('Préfet des études', 'Enseignants:READ'),
  ('Préfet des études', 'Enseignants:UPDATE'),
  ('Préfet des études', 'Examens:CREATE'),
  ('Préfet des études', 'Examens:DELETE'),
  ('Préfet des études', 'Examens:READ'),
  ('Préfet des études', 'Examens:SUSPEND'),
  ('Préfet des études', 'Examens:UPDATE'),
  ('Préfet des études', 'Frais & tarifs:READ'),
  ('Préfet des études', 'Gérer planning académique'),
  ('Préfet des études', 'Matières:CREATE'),
  ('Préfet des études', 'Matières:DELETE'),
  ('Préfet des études', 'Matières:READ'),
  ('Préfet des études', 'Matières:SUSPEND'),
  ('Préfet des études', 'Matières:UPDATE'),
  ('Préfet des études', 'Messages:CREATE'),
  ('Préfet des études', 'Messages:DELETE'),
  ('Préfet des études', 'Messages:READ'),
  ('Préfet des études', 'Messages:SUSPEND'),
  ('Préfet des études', 'Messages:UPDATE'),
  ('Préfet des études', 'Modifier notes'),
  ('Préfet des études', 'Modifier présences'),
  ('Préfet des études', 'Notes:CREATE'),
  ('Préfet des études', 'Notes:DELETE'),
  ('Préfet des études', 'Notes:READ'),
  ('Préfet des études', 'Notes:SUSPEND'),
  ('Préfet des études', 'Notes:UPDATE'),
  ('Préfet des études', 'Notifications:CREATE'),
  ('Préfet des études', 'Notifications:DELETE'),
  ('Préfet des études', 'Notifications:READ'),
  ('Préfet des études', 'Notifications:SUSPEND'),
  ('Préfet des études', 'Notifications:UPDATE'),
  ('Préfet des études', 'Organiser examens'),
  ('Préfet des études', 'Paiements:READ'),
  ('Préfet des études', 'Paramètres Établissement:READ'),
  ('Préfet des études', 'Planning de cours:CREATE'),
  ('Préfet des études', 'Planning de cours:DELETE'),
  ('Préfet des études', 'Planning de cours:READ'),
  ('Préfet des études', 'Planning de cours:SUSPEND'),
  ('Préfet des études', 'Planning de cours:UPDATE'),
  ('Préfet des études', 'Présences:CREATE'),
  ('Préfet des études', 'Présences:DELETE'),
  ('Préfet des études', 'Présences:READ'),
  ('Préfet des études', 'Présences:SUSPEND'),
  ('Préfet des études', 'Présences:UPDATE'),
  ('Préfet des études', 'Rapports:CREATE'),
  ('Préfet des études', 'Rapports:DELETE'),
  ('Préfet des études', 'Rapports:READ'),
  ('Préfet des études', 'Rapports:SUSPEND'),
  ('Préfet des études', 'Rapports:UPDATE'),
  ('Préfet des études', 'Relations:READ'),
  ('Préfet des études', 'Remplacements:CREATE'),
  ('Préfet des études', 'Remplacements:DELETE'),
  ('Préfet des études', 'Remplacements:READ'),
  ('Préfet des études', 'Remplacements:SUSPEND'),
  ('Préfet des études', 'Remplacements:UPDATE'),
  ('Préfet des études', 'Salles:CREATE'),
  ('Préfet des études', 'Salles:DELETE'),
  ('Préfet des études', 'Salles:READ'),
  ('Préfet des études', 'Salles:SUSPEND'),
  ('Préfet des études', 'Salles:UPDATE'),
  ('Préfet des études', 'Utilisateurs:READ'),
  ('Préfet des études', 'Voir classes'),
  ('Préfet des études', 'Voir élèves'),
  ('Préfet des études', 'Voir enseignants'),
  ('Préfet des études', 'Voir notes'),
  ('Préfet des études', 'Voir présences'),
  ('Directeur', 'Affectations:CREATE'),
  ('Directeur', 'Affectations:DELETE'),
  ('Directeur', 'Affectations:READ'),
  ('Directeur', 'Affectations:SUSPEND'),
  ('Directeur', 'Affectations:UPDATE'),
  ('Directeur', 'Années Académiques:READ'),
  ('Directeur', 'Announcements:CREATE'),
  ('Directeur', 'Announcements:DELETE'),
  ('Directeur', 'Announcements:READ'),
  ('Directeur', 'Announcements:SUSPEND'),
  ('Directeur', 'Announcements:UPDATE'),
  ('Directeur', 'Bulletins:CREATE'),
  ('Directeur', 'Bulletins:DELETE'),
  ('Directeur', 'Bulletins:READ'),
  ('Directeur', 'Bulletins:SUSPEND'),
  ('Directeur', 'Bulletins:UPDATE'),
  ('Directeur', 'Classes:CREATE'),
  ('Directeur', 'Classes:DELETE'),
  ('Directeur', 'Classes:READ'),
  ('Directeur', 'Classes:SUSPEND'),
  ('Directeur', 'Classes:UPDATE'),
  ('Directeur', 'Contacts:READ'),
  ('Directeur', 'Documents:CREATE'),
  ('Directeur', 'Documents:DELETE'),
  ('Directeur', 'Documents:READ'),
  ('Directeur', 'Documents:SUSPEND'),
  ('Directeur', 'Documents:UPDATE'),
  ('Directeur', 'Élèves:CREATE'),
  ('Directeur', 'Élèves:DELETE'),
  ('Directeur', 'Élèves:READ'),
  ('Directeur', 'Élèves:SUSPEND'),
  ('Directeur', 'Élèves:UPDATE'),
  ('Directeur', 'Enseignants:READ'),
  ('Directeur', 'Examens:CREATE'),
  ('Directeur', 'Examens:DELETE'),
  ('Directeur', 'Examens:READ'),
  ('Directeur', 'Examens:SUSPEND'),
  ('Directeur', 'Examens:UPDATE'),
  ('Directeur', 'Frais & tarifs:READ'),
  ('Directeur', 'Gérer paiements'),
  ('Directeur', 'Gérer utilisateurs'),
  ('Directeur', 'Matières:CREATE'),
  ('Directeur', 'Matières:DELETE'),
  ('Directeur', 'Matières:READ'),
  ('Directeur', 'Matières:SUSPEND'),
  ('Directeur', 'Matières:UPDATE'),
  ('Directeur', 'Messages:CREATE'),
  ('Directeur', 'Messages:DELETE'),
  ('Directeur', 'Messages:READ'),
  ('Directeur', 'Messages:SUSPEND'),
  ('Directeur', 'Messages:UPDATE'),
  ('Directeur', 'Modifier notes'),
  ('Directeur', 'Notes:CREATE'),
  ('Directeur', 'Notes:DELETE'),
  ('Directeur', 'Notes:READ'),
  ('Directeur', 'Notes:SUSPEND'),
  ('Directeur', 'Notes:UPDATE'),
  ('Directeur', 'Notifications:CREATE'),
  ('Directeur', 'Notifications:DELETE'),
  ('Directeur', 'Notifications:READ'),
  ('Directeur', 'Notifications:SUSPEND'),
  ('Directeur', 'Notifications:UPDATE'),
  ('Directeur', 'Paiements:READ'),
  ('Directeur', 'Paramètres Établissement:READ'),
  ('Directeur', 'Planning de cours:CREATE'),
  ('Directeur', 'Planning de cours:DELETE'),
  ('Directeur', 'Planning de cours:READ'),
  ('Directeur', 'Planning de cours:SUSPEND'),
  ('Directeur', 'Planning de cours:UPDATE'),
  ('Directeur', 'Présences:CREATE'),
  ('Directeur', 'Présences:DELETE'),
  ('Directeur', 'Présences:READ'),
  ('Directeur', 'Présences:SUSPEND'),
  ('Directeur', 'Présences:UPDATE'),
  ('Directeur', 'Rapports:CREATE'),
  ('Directeur', 'Rapports:DELETE'),
  ('Directeur', 'Rapports:READ'),
  ('Directeur', 'Rapports:SUSPEND'),
  ('Directeur', 'Rapports:UPDATE'),
  ('Directeur', 'Relations:READ'),
  ('Directeur', 'Remplacements:CREATE'),
  ('Directeur', 'Remplacements:DELETE'),
  ('Directeur', 'Remplacements:READ'),
  ('Directeur', 'Remplacements:SUSPEND'),
  ('Directeur', 'Remplacements:UPDATE'),
  ('Directeur', 'Salles:CREATE'),
  ('Directeur', 'Salles:DELETE'),
  ('Directeur', 'Salles:READ'),
  ('Directeur', 'Salles:SUSPEND'),
  ('Directeur', 'Salles:UPDATE'),
  ('Directeur', 'Utilisateurs:READ'),
  ('Directeur', 'Voir élèves'),
  ('Directeur', 'Voir rapports'),
  ('Secrétaire', 'Abonnements:READ'),
  ('Secrétaire', 'Affectations:READ'),
  ('Secrétaire', 'Announcements:CREATE'),
  ('Secrétaire', 'Announcements:DELETE'),
  ('Secrétaire', 'Announcements:READ'),
  ('Secrétaire', 'Announcements:SUSPEND'),
  ('Secrétaire', 'Announcements:UPDATE'),
  ('Secrétaire', 'Bulletins:READ'),
  ('Secrétaire', 'Classes:READ'),
  ('Secrétaire', 'Contacts:READ'),
  ('Secrétaire', 'Documents:CREATE'),
  ('Secrétaire', 'Documents:DELETE'),
  ('Secrétaire', 'Documents:READ'),
  ('Secrétaire', 'Documents:SUSPEND'),
  ('Secrétaire', 'Documents:UPDATE'),
  ('Secrétaire', 'Élèves:CREATE'),
  ('Secrétaire', 'Élèves:DELETE'),
  ('Secrétaire', 'Élèves:READ'),
  ('Secrétaire', 'Élèves:SUSPEND'),
  ('Secrétaire', 'Élèves:UPDATE'),
  ('Secrétaire', 'Enseignants:READ'),
  ('Secrétaire', 'Frais & tarifs:READ'),
  ('Secrétaire', 'Gérer appels'),
  ('Secrétaire', 'Gérer élèves'),
  ('Secrétaire', 'Gérer paiements'),
  ('Secrétaire', 'Messages:CREATE'),
  ('Secrétaire', 'Messages:DELETE'),
  ('Secrétaire', 'Messages:READ'),
  ('Secrétaire', 'Messages:SUSPEND'),
  ('Secrétaire', 'Messages:UPDATE'),
  ('Secrétaire', 'Notifications:CREATE'),
  ('Secrétaire', 'Notifications:DELETE'),
  ('Secrétaire', 'Notifications:READ'),
  ('Secrétaire', 'Notifications:SUSPEND'),
  ('Secrétaire', 'Notifications:UPDATE'),
  ('Secrétaire', 'Paiements:CREATE'),
  ('Secrétaire', 'Paiements:DELETE'),
  ('Secrétaire', 'Paiements:READ'),
  ('Secrétaire', 'Paiements:SUSPEND'),
  ('Secrétaire', 'Paiements:UPDATE'),
  ('Secrétaire', 'Présences:CREATE'),
  ('Secrétaire', 'Présences:DELETE'),
  ('Secrétaire', 'Présences:READ'),
  ('Secrétaire', 'Présences:SUSPEND'),
  ('Secrétaire', 'Présences:UPDATE'),
  ('Secrétaire', 'Rapports:READ'),
  ('Secrétaire', 'Relations:READ'),
  ('Secrétaire', 'Voir élèves'),
  ('Enseignant', 'Affectations:READ'),
  ('Enseignant', 'Années Académiques:READ'),
  ('Enseignant', 'Announcements:READ'),
  ('Enseignant', 'Bulletins:READ'),
  ('Enseignant', 'Classes:READ'),
  ('Enseignant', 'Créer notes'),
  ('Enseignant', 'Documents:READ'),
  ('Enseignant', 'Élèves:READ'),
  ('Enseignant', 'Examens:READ'),
  ('Enseignant', 'Faire appel'),
  ('Enseignant', 'Matières:READ'),
  ('Enseignant', 'Messages parents'),
  ('Enseignant', 'Messages:CREATE'),
  ('Enseignant', 'Messages:DELETE'),
  ('Enseignant', 'Messages:READ'),
  ('Enseignant', 'Messages:SUSPEND'),
  ('Enseignant', 'Messages:UPDATE'),
  ('Enseignant', 'Modifier notes'),
  ('Enseignant', 'Notes:CREATE'),
  ('Enseignant', 'Notes:DELETE'),
  ('Enseignant', 'Notes:READ'),
  ('Enseignant', 'Notes:SUSPEND'),
  ('Enseignant', 'Notes:UPDATE'),
  ('Enseignant', 'Notifications:READ'),
  ('Enseignant', 'Planning de cours:READ'),
  ('Enseignant', 'Présences:CREATE'),
  ('Enseignant', 'Présences:DELETE'),
  ('Enseignant', 'Présences:READ'),
  ('Enseignant', 'Présences:SUSPEND'),
  ('Enseignant', 'Présences:UPDATE'),
  ('Enseignant', 'Rapports:READ'),
  ('Enseignant', 'Remplacements:READ'),
  ('Enseignant', 'Salles:READ'),
  ('Enseignant', 'Voir bulletins'),
  ('Enseignant', 'Voir documents'),
  ('Enseignant', 'Voir élèves'),
  ('Enseignant', 'Voir examens'),
  ('Parent', 'Announcements:READ'),
  ('Parent', 'Bulletins:READ'),
  ('Parent', 'Classes:READ'),
  ('Parent', 'Documents:READ'),
  ('Parent', 'Élèves:READ'),
  ('Parent', 'Messages école'),
  ('Parent', 'Messages:CREATE'),
  ('Parent', 'Messages:DELETE'),
  ('Parent', 'Messages:READ'),
  ('Parent', 'Messages:SUSPEND'),
  ('Parent', 'Messages:UPDATE'),
  ('Parent', 'Notes:READ'),
  ('Parent', 'Notifications:READ'),
  ('Parent', 'Paiements:READ'),
  ('Parent', 'Présences:READ'),
  ('Parent', 'Rapports:READ'),
  ('Parent', 'Voir enfant'),
  ('Parent', 'Voir notes'),
  ('Parent', 'Voir paiements'),
  ('Parent', 'Voir présences'),
  ('Élève / Étudiant', 'Announcements:READ'),
  ('Élève / Étudiant', 'Bulletins:READ'),
  ('Élève / Étudiant', 'Classes:READ'),
  ('Élève / Étudiant', 'Documents:READ'),
  ('Élève / Étudiant', 'Élèves:READ'),
  ('Élève / Étudiant', 'Messages:CREATE'),
  ('Élève / Étudiant', 'Messages:DELETE'),
  ('Élève / Étudiant', 'Messages:READ'),
  ('Élève / Étudiant', 'Messages:SUSPEND'),
  ('Élève / Étudiant', 'Messages:UPDATE'),
  ('Élève / Étudiant', 'Notes:READ'),
  ('Élève / Étudiant', 'Notifications:READ'),
  ('Élève / Étudiant', 'Paiements:READ'),
  ('Élève / Étudiant', 'Présences:READ'),
  ('Élève / Étudiant', 'Rapports:READ'),
  ('Élève / Étudiant', 'Voir notes'),
  ('Élève / Étudiant', 'Voir paiements'),
  ('Élève / Étudiant', 'Voir présences'),
  ('Comptable', 'Frais & tarifs:READ'),
  ('Comptable', 'Gérer paiements'),
  ('Comptable', 'Impayés:READ'),
  ('Comptable', 'Paiements:CREATE'),
  ('Comptable', 'Paiements:READ'),
  ('Comptable', 'Paiements:UPDATE'),
  ('Comptable', 'Rapports:READ'),
  ('Comptable', 'Voir paiements'),
  ('Comptable', 'Voir rapports financiers'),
  ('Surveillant', 'Classes:READ'),
  ('Surveillant', 'Élèves:READ'),
  ('Surveillant', 'Gérer appels'),
  ('Surveillant', 'Gérer discipline'),
  ('Surveillant', 'Présences:CREATE'),
  ('Surveillant', 'Présences:READ'),
  ('Surveillant', 'Présences:UPDATE'),
  ('Surveillant', 'Voir élèves');

CREATE TEMP TABLE _p0_system_grants (
  role_key TEXT NOT NULL,
  module_key TEXT NOT NULL,
  can_create BOOLEAN NOT NULL,
  can_read BOOLEAN NOT NULL,
  can_update BOOLEAN NOT NULL,
  can_delete BOOLEAN NOT NULL,
  PRIMARY KEY (role_key, module_key)
) ON COMMIT DROP;

INSERT INTO _p0_system_grants (role_key, module_key, can_create, can_read, can_update, can_delete) VALUES
  ('SUPER_ADMIN', 'countries', true, true, true, true),
  ('SUPER_ADMIN', 'schools', true, true, true, true),
  ('SUPER_ADMIN', 'subscriptions', true, true, true, true),
  ('SUPER_ADMIN', 'contacts', true, true, true, true),
  ('SUPER_ADMIN', 'relations', true, true, true, true),
  ('SUPER_ADMIN', 'users', true, true, true, true),
  ('SUPER_ADMIN', 'classes', true, true, true, true),
  ('SUPER_ADMIN', 'students', true, true, true, true),
  ('SUPER_ADMIN', 'teachers', true, true, true, true),
  ('SUPER_ADMIN', 'assignments', true, true, true, true),
  ('SUPER_ADMIN', 'attendance', true, true, true, true),
  ('SUPER_ADMIN', 'grades', true, true, true, true),
  ('SUPER_ADMIN', 'report_cards', true, true, true, true),
  ('SUPER_ADMIN', 'payments', true, true, true, true),
  ('SUPER_ADMIN', 'fees', true, true, true, true),
  ('SUPER_ADMIN', 'notifications', true, true, true, true),
  ('SUPER_ADMIN', 'announcements', true, true, true, true),
  ('SUPER_ADMIN', 'messages', true, true, true, true),
  ('SUPER_ADMIN', 'documents', true, true, true, true),
  ('SUPER_ADMIN', 'reports', true, true, true, true),
  ('SUPER_ADMIN', 'school_settings', true, true, true, true),
  ('SUPER_ADMIN', 'academic_years', true, true, true, true),
  ('SUPER_ADMIN', 'subjects', true, true, true, true),
  ('SUPER_ADMIN', 'exams', true, true, true, true),
  ('SUPER_ADMIN', 'planning', true, true, true, true),
  ('SUPER_ADMIN', 'rooms', true, true, true, true),
  ('SUPER_ADMIN', 'replacements', true, true, true, true),
  ('COUNTRY_ADMIN', 'countries', true, true, true, true),
  ('COUNTRY_ADMIN', 'schools', true, true, true, true),
  ('COUNTRY_ADMIN', 'subscriptions', true, true, true, true),
  ('COUNTRY_ADMIN', 'contacts', false, true, false, false),
  ('COUNTRY_ADMIN', 'users', true, true, true, true),
  ('COUNTRY_ADMIN', 'notifications', true, true, true, true),
  ('COUNTRY_ADMIN', 'announcements', true, true, true, true),
  ('COUNTRY_ADMIN', 'messages', true, true, true, true),
  ('COUNTRY_ADMIN', 'reports', false, true, false, false),
  ('SCHOOL_ADMIN', 'contacts', true, true, true, true),
  ('SCHOOL_ADMIN', 'relations', true, true, true, true),
  ('SCHOOL_ADMIN', 'users', true, true, true, true),
  ('SCHOOL_ADMIN', 'classes', true, true, true, true),
  ('SCHOOL_ADMIN', 'students', true, true, true, true),
  ('SCHOOL_ADMIN', 'teachers', true, true, true, false),
  ('SCHOOL_ADMIN', 'assignments', true, true, true, false),
  ('SCHOOL_ADMIN', 'attendance', false, true, true, false),
  ('SCHOOL_ADMIN', 'grades', false, true, true, false),
  ('SCHOOL_ADMIN', 'report_cards', false, true, true, false),
  ('SCHOOL_ADMIN', 'payments', true, true, true, true),
  ('SCHOOL_ADMIN', 'fees', true, true, true, true),
  ('SCHOOL_ADMIN', 'notifications', true, true, true, true),
  ('SCHOOL_ADMIN', 'announcements', true, true, true, true),
  ('SCHOOL_ADMIN', 'messages', true, true, true, true),
  ('SCHOOL_ADMIN', 'documents', true, true, true, true),
  ('SCHOOL_ADMIN', 'reports', true, true, true, true),
  ('SCHOOL_ADMIN', 'school_settings', true, true, true, true),
  ('SCHOOL_ADMIN', 'academic_years', true, true, true, true),
  ('SCHOOL_ADMIN', 'subjects', true, true, true, true),
  ('SCHOOL_ADMIN', 'exams', true, true, true, true),
  ('SCHOOL_ADMIN', 'planning', true, true, true, true),
  ('SCHOOL_ADMIN', 'rooms', true, true, true, true),
  ('SCHOOL_ADMIN', 'replacements', true, true, true, true),
  ('PROVISEUR', 'contacts', false, true, false, false),
  ('PROVISEUR', 'relations', false, true, false, false),
  ('PROVISEUR', 'users', false, true, false, false),
  ('PROVISEUR', 'classes', true, true, true, true),
  ('PROVISEUR', 'students', true, true, true, true),
  ('PROVISEUR', 'teachers', false, true, false, false),
  ('PROVISEUR', 'assignments', true, true, true, true),
  ('PROVISEUR', 'attendance', true, true, true, true),
  ('PROVISEUR', 'grades', true, true, true, true),
  ('PROVISEUR', 'report_cards', true, true, true, true),
  ('PROVISEUR', 'payments', false, true, false, false),
  ('PROVISEUR', 'fees', false, true, false, false),
  ('PROVISEUR', 'notifications', true, true, true, true),
  ('PROVISEUR', 'announcements', true, true, true, true),
  ('PROVISEUR', 'messages', true, true, true, true),
  ('PROVISEUR', 'documents', true, true, true, true),
  ('PROVISEUR', 'reports', true, true, true, true),
  ('PROVISEUR', 'school_settings', false, true, false, false),
  ('PROVISEUR', 'academic_years', false, true, true, false),
  ('PROVISEUR', 'subjects', true, true, true, true),
  ('PROVISEUR', 'exams', true, true, true, true),
  ('PROVISEUR', 'planning', true, true, true, true),
  ('PROVISEUR', 'rooms', true, true, true, true),
  ('PROVISEUR', 'replacements', true, true, true, true),
  ('PREFET_ETUDES', 'contacts', false, true, false, false),
  ('PREFET_ETUDES', 'relations', false, true, false, false),
  ('PREFET_ETUDES', 'users', false, true, false, false),
  ('PREFET_ETUDES', 'classes', true, true, true, true),
  ('PREFET_ETUDES', 'students', true, true, true, true),
  ('PREFET_ETUDES', 'teachers', false, true, true, true),
  ('PREFET_ETUDES', 'assignments', true, true, true, true),
  ('PREFET_ETUDES', 'attendance', true, true, true, true),
  ('PREFET_ETUDES', 'grades', true, true, true, true),
  ('PREFET_ETUDES', 'report_cards', true, true, true, true),
  ('PREFET_ETUDES', 'payments', false, true, false, false),
  ('PREFET_ETUDES', 'fees', false, true, false, false),
  ('PREFET_ETUDES', 'notifications', true, true, true, true),
  ('PREFET_ETUDES', 'announcements', true, true, true, true),
  ('PREFET_ETUDES', 'messages', true, true, true, true),
  ('PREFET_ETUDES', 'documents', true, true, true, true),
  ('PREFET_ETUDES', 'reports', true, true, true, true),
  ('PREFET_ETUDES', 'school_settings', false, true, false, false),
  ('PREFET_ETUDES', 'academic_years', false, true, false, false),
  ('PREFET_ETUDES', 'subjects', true, true, true, true),
  ('PREFET_ETUDES', 'exams', true, true, true, true),
  ('PREFET_ETUDES', 'planning', true, true, true, true),
  ('PREFET_ETUDES', 'rooms', true, true, true, true),
  ('PREFET_ETUDES', 'replacements', true, true, true, true),
  ('PRINCIPAL', 'contacts', false, true, false, false),
  ('PRINCIPAL', 'relations', false, true, false, false),
  ('PRINCIPAL', 'users', true, true, true, true),
  ('PRINCIPAL', 'classes', true, true, true, true),
  ('PRINCIPAL', 'students', true, true, true, true),
  ('PRINCIPAL', 'teachers', false, true, false, false),
  ('PRINCIPAL', 'assignments', true, true, true, true),
  ('PRINCIPAL', 'attendance', true, true, true, true),
  ('PRINCIPAL', 'grades', true, true, true, true),
  ('PRINCIPAL', 'report_cards', true, true, true, true),
  ('PRINCIPAL', 'payments', true, true, true, true),
  ('PRINCIPAL', 'fees', false, true, false, false),
  ('PRINCIPAL', 'notifications', true, true, true, true),
  ('PRINCIPAL', 'announcements', true, true, true, true),
  ('PRINCIPAL', 'messages', true, true, true, true),
  ('PRINCIPAL', 'documents', true, true, true, true),
  ('PRINCIPAL', 'reports', true, true, true, true),
  ('PRINCIPAL', 'school_settings', false, true, false, false),
  ('PRINCIPAL', 'academic_years', false, true, false, false),
  ('PRINCIPAL', 'subjects', true, true, true, true),
  ('PRINCIPAL', 'exams', true, true, true, true),
  ('PRINCIPAL', 'planning', true, true, true, true),
  ('PRINCIPAL', 'rooms', true, true, true, true),
  ('PRINCIPAL', 'replacements', true, true, true, true),
  ('SECRETARY', 'subscriptions', false, true, false, false),
  ('SECRETARY', 'contacts', false, true, false, false),
  ('SECRETARY', 'relations', false, true, false, false),
  ('SECRETARY', 'classes', false, true, false, false),
  ('SECRETARY', 'students', true, true, true, true),
  ('SECRETARY', 'teachers', false, true, false, false),
  ('SECRETARY', 'assignments', false, true, false, false),
  ('SECRETARY', 'attendance', true, true, true, true),
  ('SECRETARY', 'report_cards', false, true, false, false),
  ('SECRETARY', 'payments', true, true, true, true),
  ('SECRETARY', 'fees', false, true, false, false),
  ('SECRETARY', 'notifications', true, true, true, true),
  ('SECRETARY', 'announcements', true, true, true, true),
  ('SECRETARY', 'messages', true, true, true, true),
  ('SECRETARY', 'documents', true, true, true, true),
  ('SECRETARY', 'reports', false, true, false, false),
  ('TEACHER', 'classes', false, true, false, false),
  ('TEACHER', 'students', false, true, false, false),
  ('TEACHER', 'assignments', false, true, false, false),
  ('TEACHER', 'attendance', true, true, true, true),
  ('TEACHER', 'grades', true, true, true, true),
  ('TEACHER', 'report_cards', false, true, false, false),
  ('TEACHER', 'notifications', false, true, false, false),
  ('TEACHER', 'announcements', false, true, false, false),
  ('TEACHER', 'messages', true, true, true, true),
  ('TEACHER', 'documents', false, true, false, false),
  ('TEACHER', 'reports', false, true, false, false),
  ('TEACHER', 'academic_years', false, true, false, false),
  ('TEACHER', 'subjects', false, true, false, false),
  ('TEACHER', 'exams', false, true, false, false),
  ('TEACHER', 'planning', false, true, false, false),
  ('TEACHER', 'rooms', false, true, false, false),
  ('TEACHER', 'replacements', false, true, false, false),
  ('PARENT', 'classes', false, true, false, false),
  ('PARENT', 'students', false, true, false, false),
  ('PARENT', 'attendance', false, true, false, false),
  ('PARENT', 'grades', false, true, false, false),
  ('PARENT', 'report_cards', false, true, false, false),
  ('PARENT', 'payments', false, true, false, false),
  ('PARENT', 'notifications', false, true, false, false),
  ('PARENT', 'announcements', false, true, false, false),
  ('PARENT', 'messages', true, true, true, true),
  ('PARENT', 'documents', false, true, false, false),
  ('PARENT', 'reports', false, true, false, false),
  ('STUDENT', 'classes', false, true, false, false),
  ('STUDENT', 'students', false, true, false, false),
  ('STUDENT', 'attendance', false, true, false, false),
  ('STUDENT', 'grades', false, true, false, false),
  ('STUDENT', 'report_cards', false, true, false, false),
  ('STUDENT', 'payments', false, true, false, false),
  ('STUDENT', 'notifications', false, true, false, false),
  ('STUDENT', 'announcements', false, true, false, false),
  ('STUDENT', 'messages', true, true, true, true),
  ('STUDENT', 'documents', false, true, false, false),
  ('STUDENT', 'reports', false, true, false, false),
  ('ACCOUNTANT', 'payments', true, true, true, true),
  ('ACCOUNTANT', 'fees', false, true, false, false),
  ('ACCOUNTANT', 'unpaid', false, true, false, false),
  ('ACCOUNTANT', 'reports', false, true, false, false),
  ('SUPERVISOR', 'classes', false, true, false, false),
  ('SUPERVISOR', 'students', false, true, false, false),
  ('SUPERVISOR', 'attendance', true, true, true, true);

-- Ambiguïté : plusieurs lignes actives pour un même rôle système.
DO $$
DECLARE
  ambiguous_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO ambiguous_count
  FROM (
    SELECT lower(er.role_name)
    FROM establishment_roles er
    JOIN _p0_system_roles sr
      ON lower(er.role_name) = lower(sr.role_name)
      OR upper(er.role_code) = upper(sr.role_code)
    GROUP BY lower(er.role_name)
    HAVING COUNT(*) > 1
  ) dupes;
  IF ambiguous_count > 0 THEN
    RAISE EXCEPTION 'SYSTEM_ROLES_RECONCILIATION_AMBIGUOUS: % rôle(s) système en double', ambiguous_count;
  END IF;
END $$;

-- Alias de codes historiques (enseignant, prefet_des_etudes, …) → clé système
CREATE TEMP TABLE _p0_role_code_aliases (
  role_name TEXT NOT NULL,
  role_code TEXT NOT NULL,
  PRIMARY KEY (role_name, role_code)
) ON COMMIT DROP;

INSERT INTO _p0_role_code_aliases (role_name, role_code) VALUES
  ('Super Administrateur Somafrik', 'SUPER_ADMIN'),
  ('Admin Pays', 'COUNTRY_ADMIN'),
  ('Admin School', 'SCHOOL_ADMIN'),
  ('Proviseur', 'PROVISEUR'),
  ('Préfet des études', 'PREFET_ETUDES'),
  ('Préfet des études', 'PREFET_DES_ETUDES'),
  ('Directeur', 'PRINCIPAL'),
  ('Directeur', 'DIRECTEUR'),
  ('Secrétaire', 'SECRETARY'),
  ('Secrétaire', 'SECRETAIRE'),
  ('Enseignant', 'TEACHER'),
  ('Enseignant', 'ENSEIGNANT'),
  ('Parent', 'PARENT'),
  ('Élève / Étudiant', 'STUDENT'),
  ('Élève / Étudiant', 'ELEVE_ETUDIANT'),
  ('Élève / Étudiant', 'ELEVE'),
  ('Comptable', 'ACCOUNTANT'),
  ('Comptable', 'COMPTABLE'),
  ('Surveillant', 'SUPERVISOR'),
  ('Surveillant', 'SURVEILLANT');

INSERT INTO establishment_roles (role_code, role_name, scope, display_order, status, school_assignable)
SELECT sr.role_code, sr.role_name, sr.scope, sr.display_order, 'active', sr.school_assignable
FROM _p0_system_roles sr
WHERE NOT EXISTS (
  SELECT 1 FROM establishment_roles er
  WHERE lower(er.role_name) = lower(sr.role_name)
     OR upper(er.role_code) = upper(sr.role_code)
);

INSERT INTO establishment_role_permissions (role_id, permission)
SELECT DISTINCT er.id, sp.permission
FROM _p0_system_permissions sp
JOIN establishment_roles er
  ON lower(er.role_name) = lower(sp.role_name)
  OR upper(er.role_code) IN (
    SELECT upper(alias.role_code)
    FROM _p0_role_code_aliases alias
    WHERE lower(alias.role_name) = lower(sp.role_name)
  )
ON CONFLICT (role_id, permission) DO NOTHING;

INSERT INTO establishment_role_delegation_permissions (role_id, permission)
SELECT DISTINCT er.id, sp.permission
FROM _p0_system_permissions sp
JOIN establishment_roles er
  ON lower(er.role_name) = lower(sp.role_name)
  OR upper(er.role_code) IN (
    SELECT upper(alias.role_code)
    FROM _p0_role_code_aliases alias
    WHERE lower(alias.role_name) = lower(sp.role_name)
  )
ON CONFLICT (role_id, permission) DO NOTHING;

INSERT INTO functional_modules (module_key, module_name, applies_web, applies_mobile, display_order, updated_at)
SELECT module_key, module_name, applies_web, applies_mobile, display_order, NOW()
FROM (VALUES
  ('countries', 'Pays', TRUE, TRUE, 10),
  ('schools', 'Établissements', TRUE, TRUE, 20),
  ('subscriptions', 'Abonnements', TRUE, FALSE, 30),
  ('contacts', 'Contacts', TRUE, FALSE, 40),
  ('relations', 'Relations', TRUE, FALSE, 50),
  ('users', 'Utilisateurs', TRUE, TRUE, 60),
  ('role_permissions', 'Droits par rôle', TRUE, TRUE, 70),
  ('education_reference', 'Référentiels pédagogiques', TRUE, FALSE, 80),
  ('classes', 'Classes', TRUE, TRUE, 90),
  ('students', 'Élèves', TRUE, TRUE, 100),
  ('teachers', 'Enseignants', TRUE, TRUE, 110),
  ('assignments', 'Affectations', TRUE, TRUE, 120),
  ('attendance', 'Présences', TRUE, TRUE, 130),
  ('grades', 'Notes', TRUE, TRUE, 140),
  ('report_cards', 'Bulletins', TRUE, TRUE, 150),
  ('payments', 'Paiements', TRUE, TRUE, 160),
  ('fees', 'Frais & tarifs', TRUE, FALSE, 170),
  ('unpaid', 'Impayés', TRUE, FALSE, 180),
  ('notifications', 'Notifications', TRUE, TRUE, 190),
  ('announcements', 'Announcements', TRUE, TRUE, 195),
  ('messages', 'Messages', TRUE, TRUE, 200),
  ('documents', 'Documents', TRUE, TRUE, 210),
  ('reports', 'Rapports', TRUE, TRUE, 220),
  ('school_settings', 'Paramètres Établissement', TRUE, TRUE, 230),
  ('academic_years', 'Années Académiques', TRUE, TRUE, 240),
  ('subjects', 'Matières', TRUE, TRUE, 250),
  ('exams', 'Examens', TRUE, TRUE, 260),
  ('planning', 'Planning de cours', TRUE, FALSE, 270),
  ('rooms', 'Salles', TRUE, FALSE, 280),
  ('replacements', 'Remplacements', TRUE, FALSE, 290)
) AS catalog(module_key, module_name, applies_web, applies_mobile, display_order)
ON CONFLICT (module_key) DO UPDATE SET
  module_name = EXCLUDED.module_name,
  applies_web = EXCLUDED.applies_web,
  applies_mobile = EXCLUDED.applies_mobile,
  display_order = EXCLUDED.display_order,
  updated_at = NOW();

INSERT INTO role_module_permissions (
  role_key, scope_type, country_id, school_id, module_key,
  can_create, can_read, can_update, can_delete, status, version,
  created_by, updated_by, created_at, updated_at
)
SELECT
  sg.role_key, 'global', NULL, NULL, sg.module_key,
  sg.can_create, sg.can_read, sg.can_update, sg.can_delete,
  'active', 1,
  'bootstrap-system-roles-reconciliation-p0',
  'bootstrap-system-roles-reconciliation-p0',
  NOW(), NOW()
FROM _p0_system_grants sg
WHERE NOT EXISTS (
  SELECT 1 FROM role_module_permissions rmp
  WHERE rmp.status = 'active'
    AND upper(rmp.role_key) = upper(sg.role_key)
    AND rmp.scope_type = 'global'
    AND rmp.module_key = sg.module_key
    AND rmp.country_id IS NULL
    AND rmp.school_id IS NULL
);

-- Pas d'OR sur un grant existant : une révocation Superadmin (ex. Notes:CREATE)
-- ne doit pas être réintroduite. Seuls les modules absents sont insérés.

COMMIT;
