#!/usr/bin/env bash
#
# Shared helpers for the Cloud Agent install/start scripts.
# Sourced by cloud-agent-install.sh and cloud-agent-start.sh.

if [ -z "${REPO_ROOT:-}" ]; then
  REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fi

# Database connection settings used by the local dev backend.
SOMAFRIK_PG_VERSION="${SOMAFRIK_PG_VERSION:-16}"
SOMAFRIK_PG_CLUSTER="${SOMAFRIK_PG_CLUSTER:-main}"
SOMAFRIK_DB_NAME="${SOMAFRIK_DB_NAME:-somafrik}"
SOMAFRIK_DB_USER="${SOMAFRIK_DB_USER:-somafrik}"
SOMAFRIK_DB_PASSWORD="${SOMAFRIK_DB_PASSWORD:-somafrik123}"
SOMAFRIK_DB_PORT="${SOMAFRIK_DB_PORT:-5432}"

# Start the PostgreSQL cluster if it is not already online (no systemd in the VM).
somafrik_pg_start() {
  if sudo pg_lsclusters -h 2>/dev/null | awk '{print $4}' | grep -q '^online$'; then
    echo "   PostgreSQL cluster already online."
    return 0
  fi
  sudo pg_ctlcluster "$SOMAFRIK_PG_VERSION" "$SOMAFRIK_PG_CLUSTER" start || true
  # Wait for readiness.
  for _ in $(seq 1 30); do
    if sudo -u postgres pg_isready -q -p "$SOMAFRIK_DB_PORT" 2>/dev/null; then
      echo "   PostgreSQL is ready on port ${SOMAFRIK_DB_PORT}."
      return 0
    fi
    sleep 1
  done
  echo "   WARNING: PostgreSQL did not report ready in time." >&2
  return 1
}

# Create the application role and database if they do not exist (idempotent).
somafrik_pg_ensure_role_db() {
  if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='${SOMAFRIK_DB_USER}'" | grep -q 1; then
    sudo -u postgres psql -v ON_ERROR_STOP=1 \
      -c "CREATE ROLE ${SOMAFRIK_DB_USER} LOGIN PASSWORD '${SOMAFRIK_DB_PASSWORD}' CREATEDB;"
  fi
  if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='${SOMAFRIK_DB_NAME}'" | grep -q 1; then
    sudo -u postgres createdb -O "$SOMAFRIK_DB_USER" "$SOMAFRIK_DB_NAME"
  fi
}

# Create local .env and Mobile/.env.local from the examples if they are missing.
# These files are gitignored; they are generated per-environment, never committed.
somafrik_write_env_files() {
  local db_url="postgresql://${SOMAFRIK_DB_USER}:${SOMAFRIK_DB_PASSWORD}@localhost:${SOMAFRIK_DB_PORT}/${SOMAFRIK_DB_NAME}"

  if [ ! -f "$REPO_ROOT/.env" ]; then
    cat > "$REPO_ROOT/.env" <<ENV
# Somafrik — Cloud Agent native dev (generated by cloud-agent scripts).
NODE_ENV=development
PORT=5000
BACKEND_PORT=5000
DATABASE_URL=${db_url}
POSTGRES_HOST=localhost
POSTGRES_PORT=${SOMAFRIK_DB_PORT}
POSTGRES_DB=${SOMAFRIK_DB_NAME}
POSTGRES_USER=${SOMAFRIK_DB_USER}
POSTGRES_PASSWORD=${SOMAFRIK_DB_PASSWORD}
POSTGRES_HOST_PORT=${SOMAFRIK_DB_PORT}
JWT_SECRET=cloud-agent-dev-secret-change-me-please-32chars
CORS_ORIGINS=http://localhost:5000,http://127.0.0.1:5000,http://localhost:5173,http://127.0.0.1:5173,http://localhost:8083,http://127.0.0.1:8083
WEB_DEV_PORT=5173
SOMAFRIK_DB_REQUIRED=true
SOMAFRIK_SKIP_DEMO_SEED=false
SOMAFRIK_DISABLE_LOGIN_LOCKOUT=true
JSON_BODY_LIMIT=1mb
EXPO_PORT=8083
ENV
    echo "   Wrote .env"
  else
    echo "   .env already present; leaving as-is."
  fi

  if [ ! -f "$REPO_ROOT/Mobile/.env.local" ] && [ -f "$REPO_ROOT/Mobile/.env.example" ]; then
    cat > "$REPO_ROOT/Mobile/.env.local" <<ENV
LAN_IP=127.0.0.1
EXPO_PORT=8083
REACT_NATIVE_PACKAGER_HOSTNAME=127.0.0.1
EXPO_PUBLIC_API_URL=http://127.0.0.1:5000
EXPO_PUBLIC_DEMO_MODE=false
ENV
    echo "   Wrote Mobile/.env.local"
  fi
}
