/** État BackOffice vide (aucune donnée métier). */
function buildEmptyBackOfficeState() {
  return {
    schools: [],
    users: [],
    countries: [],
    contacts: [],
    relations: [],
    subscriptions: [],
    subscriptionOffers: [],
    subscriptionPayments: [],
    subscriptionInvoices: [],
    subscriptionDiscounts: [],
    subscriptionAuditLog: [],
    notifications: [],
    students: [],
    teachers: [],
    classes: [],
    courses: [],
    assignments: [],
    payments: [],
    paymentStatuses: [],
    feeGrids: [],
    schoolFeeItems: [],
    studentFees: [],
    feeTariffHistory: [],
    feeGrids: [],
    schoolFeeItems: [],
    studentFees: [],
    feeTariffHistory: [],
    presences: [],
    notes: [],
    evaluations: [],
    exams: [],
    bulletins: [],
    documents: [],
    academicConfigs: {},
    announcements: [],
    messages: [],
    auditLog: [],
    rolePermissions: {},
    dashboardChartConfig: { platform: {}, establishment: {} },
    deletedRows: {},
    updatedAt: new Date().toISOString(),
  };
}

module.exports = { buildEmptyBackOfficeState };
