"use strict";

/**
 * F6 — matrice endpoint Finance / action RBAC.
 * Les permissions sont le référentiel canonique existant.
 * Aucune route mutation ne réutilise POST /api/payments par commodité.
 */

const FINANCE_RBAC_ROUTE_MATRIX = [
  {
    method: "GET",
    path: "/api/finance/catalog",
    action: "Lire le catalogue Finance (moyens, types)",
    resource: "Paiements / Frais & tarifs",
    permission: "Paiements:READ | Frais & tarifs:READ",
    routeKey: "GET /api/finance/catalog",
    secondaryGuard: "",
  },
  {
    method: "GET",
    path: "/api/finance/payment-student-options",
    action: "Lister les élèves pour un encaissement Comptable",
    resource: "Paiements",
    permission: "Paiements:READ",
    routeKey: "GET /api/finance/payment-student-options",
    secondaryGuard: "tenant schoolCode — pas Élèves:READ",
  },
  {
    method: "GET",
    path: "/api/finance/payment-methods",
    action: "Lire les moyens de paiement",
    resource: "Paiements / Paramètres",
    permission: "Paiements:READ | Frais & tarifs:READ | Paramètres Établissement:READ",
    routeKey: "GET /api/finance/payment-methods",
    secondaryGuard: "",
  },
  {
    method: "PUT",
    path: "/api/finance/payment-methods",
    action: "Remplacer le catalogue des moyens",
    resource: "Frais & tarifs / Paramètres Établissement",
    permission: "Frais & tarifs:UPDATE | Paramètres Établissement:UPDATE",
    routeKey: "PUT /api/finance/payment-methods",
    secondaryGuard: "canManagePaymentMethods",
  },
  {
    method: "GET",
    path: "/api/finance/payment-statuses",
    action: "Lire les statuts de paiement",
    resource: "Paiements",
    permission: "Paiements:READ",
    routeKey: "GET /api/finance/payment-statuses",
    secondaryGuard: "",
  },
  {
    method: "POST",
    path: "/api/finance/payment-statuses",
    action: "Créer un statut de paiement",
    resource: "Paiements",
    permission: "Paiements:UPDATE",
    routeKey: "POST /api/finance/payment-statuses",
    secondaryGuard: "canManagePaymentStatuses",
  },
  {
    method: "PATCH",
    path: "/api/finance/payment-statuses/:statusId",
    action: "Modifier un statut de paiement",
    resource: "Paiements",
    permission: "Paiements:UPDATE",
    routeKey: "PATCH /api/finance/payment-statuses/:statusId",
    secondaryGuard: "canManagePaymentStatuses",
  },
  {
    method: "GET",
    path: "/api/finance/fee-grids",
    action: "Lister les grilles tarifaires",
    resource: "Frais & tarifs",
    permission: "Frais & tarifs:READ | Paiements:READ | Impayés:READ",
    routeKey: "GET /api/finance/fee-grids",
    secondaryGuard: "",
  },
  {
    method: "POST",
    path: "/api/finance/fee-grids",
    action: "Créer une grille tarifaire",
    resource: "Frais & tarifs",
    permission: "Frais & tarifs:CREATE | Frais & tarifs:UPDATE",
    routeKey: "POST /api/finance/fee-grids",
    secondaryGuard: "canManageFeeGrids",
  },
  {
    method: "GET",
    path: "/api/finance/fee-grids/:gridId",
    action: "Lire une grille tarifaire",
    resource: "Frais & tarifs",
    permission: "Frais & tarifs:READ | Paiements:READ | Impayés:READ",
    routeKey: "GET /api/finance/fee-grids",
    secondaryGuard: "tenant 404",
  },
  {
    method: "PATCH",
    path: "/api/finance/fee-grids/:gridId",
    action: "Modifier une grille tarifaire",
    resource: "Frais & tarifs",
    permission: "Frais & tarifs:UPDATE",
    routeKey: "PATCH /api/finance/fee-grids/:gridId",
    secondaryGuard: "canManageFeeGrids",
  },
  {
    method: "POST",
    path: "/api/finance/fee-grids/:gridId/activate",
    action: "Activer une grille",
    resource: "Frais & tarifs",
    permission: "Frais & tarifs:UPDATE",
    routeKey: "POST /api/finance/fee-grids/:gridId/activate",
    secondaryGuard: "canManageFeeGrids",
  },
  {
    method: "POST",
    path: "/api/finance/fee-grids/:gridId/deactivate",
    action: "Désactiver une grille",
    resource: "Frais & tarifs",
    permission: "Frais & tarifs:UPDATE",
    routeKey: "POST /api/finance/fee-grids/:gridId/deactivate",
    secondaryGuard: "canManageFeeGrids",
  },
  {
    method: "POST",
    path: "/api/finance/fee-grids/:gridId/apply",
    action: "Appliquer une grille (obligations)",
    resource: "Frais & tarifs",
    permission: "Frais & tarifs:UPDATE",
    routeKey: "POST /api/finance/fee-grids/:gridId/apply",
    secondaryGuard: "canManageFeeGrids",
  },
  {
    method: "GET",
    path: "/api/finance/student-fees",
    action: "Lire la projection des obligations",
    resource: "Impayés / Paiements / Frais & tarifs",
    permission: "Impayés:READ | Paiements:READ | Frais & tarifs:READ",
    routeKey: "GET /api/finance/student-fees",
    secondaryGuard: "",
  },
  {
    method: "GET",
    path: "/api/finance/student-fees/:obligationId",
    action: "Lire une obligation",
    resource: "Impayés / Paiements / Frais & tarifs",
    permission: "Impayés:READ | Paiements:READ | Frais & tarifs:READ",
    routeKey: "GET /api/finance/student-fees",
    secondaryGuard: "",
  },
  {
    method: "POST",
    path: "/api/finance/student-fees/:obligationId/adjust",
    action: "Ajuster une obligation",
    resource: "Paiements / Frais & tarifs",
    permission: "Paiements:UPDATE | Frais & tarifs:UPDATE",
    routeKey: "POST /api/finance/student-fees/:obligationId/adjust",
    secondaryGuard: "canAdjustStudentFee",
  },
  {
    method: "POST",
    path: "/api/finance/reconcile-payment-allocations",
    action: "Réconciliation allocations (admin)",
    resource: "Paiements",
    permission: "Paiements:UPDATE",
    routeKey: "POST /api/finance/reconcile-payment-allocations",
    secondaryGuard: "",
  },
  {
    method: "GET",
    path: "/api/payments",
    action: "Lister les encaissements",
    resource: "Paiements",
    permission: "Paiements:READ",
    routeKey: "GET /api/payments",
    secondaryGuard: "",
  },
  {
    method: "GET",
    path: "/api/payments/:paymentId",
    action: "Lire un encaissement",
    resource: "Paiements",
    permission: "Paiements:READ",
    routeKey: "GET /api/payments",
    secondaryGuard: "",
  },
  {
    method: "POST",
    path: "/api/payments",
    action: "Enregistrer un encaissement",
    resource: "Paiements",
    permission: "Paiements:CREATE | Paiements:UPDATE",
    routeKey: "POST /api/payments",
    secondaryGuard: "obligationId ou Non imputé (F4/F5)",
  },
  {
    method: "POST",
    path: "/api/payments/:paymentId/cancel",
    action: "Annuler un encaissement",
    resource: "Paiements",
    permission: "Paiements:UPDATE",
    routeKey: "POST /api/payments/:paymentId/cancel",
    secondaryGuard: "canCancelPayment — CREATE seul insuffisant",
  },
  {
    method: "GET",
    path: "/api/backoffice/finance/unpaid",
    action: "Lister les impayés",
    resource: "Impayés",
    permission: "Impayés:READ | Paiements:READ | Frais & tarifs:READ",
    routeKey: "GET /api/backoffice/finance/unpaid",
    secondaryGuard: "",
  },
  {
    method: "GET",
    path: "/api/backoffice/finance/unpaid/:studentId",
    action: "Détail impayés élève",
    resource: "Impayés",
    permission: "Impayés:READ | Paiements:READ | Frais & tarifs:READ",
    routeKey: "GET /api/backoffice/finance/unpaid",
    secondaryGuard: "",
  },
  {
    method: "GET",
    path: "/api/backoffice/finance/unpaid/:studentId/reminders",
    action: "Historique des relances",
    resource: "Impayés",
    permission: "Impayés:READ | Paiements:READ | Frais & tarifs:READ",
    routeKey: "GET /api/backoffice/finance/unpaid",
    secondaryGuard: "",
  },
  {
    method: "POST",
    path: "/api/backoffice/finance/unpaid/:studentId/reminders",
    action: "Envoyer une relance",
    resource: "Impayés",
    permission: "Impayés:CREATE | Paiements:UPDATE",
    routeKey: "POST /api/backoffice/finance/unpaid/reminders",
    secondaryGuard: "canForceReminder si force=true",
  },
  {
    method: "GET",
    path: "/api/students/:id/payments",
    action: "Paiements d'un élève (fiche)",
    resource: "Paiements",
    permission: "auth + périmètre élève (parent/élève ou Paiements:READ via /payments)",
    routeKey: "",
    secondaryGuard: "resolveAuthorizedStudentForPrincipal — pas Élèves:READ élargi",
  },
];

module.exports = { FINANCE_RBAC_ROUTE_MATRIX };
